[package]
name = "fake-royal"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
postgres = ["fake-chat/postgres"]
redis = ["fake-chat/redis"]
consul = ["kim-naming/consul"]

[dependencies]
axum = { workspace = true, features = ["json"] }
bytes.workspace = true
fake-chat = { path = "../fake-chat" }
kim-naming.workspace = true
kim-protocol.workspace = true
prost.workspace = true
reqwest.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml = "0.8"
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
