// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'failure.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `abandon_yield`, `aborted`, `action_required`, `arm_yield_watch`, `attach_codex`, `base`, `begin_run`, `completed`, `disarm_yield_watch`, `failed`, `finish_turn`, `listener_released`, `map_host_err`, `open_request`, `operation_started`, `recreate_host`, `recv_op_id`, `resolved_from_opts`, `session_ready`, `set_phase_if_current`, `shared_new`, `sleep_bounded`, `spawn_host_pump`, `spawn_on_current`, `start_prompt`, `text_delta`, `tool_finished`, `tool_request`, `tool_started`, `turn_is_current`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AgentSession`, `SessionOpenOpts`, `Shared`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `reconfigure`, `session_open`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `abort`, `close`, `complete_tool`, `default`, `listen`, `park`, `prompt_with_context`, `prompt`, `respond_permission`, `resume`, `snapshot`, `steer`

Future<List<String>> fetchSupportedModels({
  required String llmBackend,
  required String baseUrl,
  required String apiKey,
}) => AgentRustLib.instance.api.crateApiSessionFetchSupportedModels(
  llmBackend: llmBackend,
  baseUrl: baseUrl,
  apiKey: apiKey,
);

Future<List<String>> listBuiltinProfiles() =>
    AgentRustLib.instance.api.crateApiSessionListBuiltinProfiles();

Future<List<String>> listBundledProviders() =>
    AgentRustLib.instance.api.crateApiSessionListBundledProviders();

class AgentUiEvent {
  final String kind;
  final String operationId;
  final String callId;
  final String name;
  final String delta;
  final String argumentsJson;
  final String outputPreview;
  final bool ok;
  final String stopReason;
  final String message;
  final BigInt inputTokens;
  final BigInt outputTokens;
  final List<String> resumedOps;
  final bool recentlyActive;

  const AgentUiEvent({
    required this.kind,
    required this.operationId,
    required this.callId,
    required this.name,
    required this.delta,
    required this.argumentsJson,
    required this.outputPreview,
    required this.ok,
    required this.stopReason,
    required this.message,
    required this.inputTokens,
    required this.outputTokens,
    required this.resumedOps,
    required this.recentlyActive,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      operationId.hashCode ^
      callId.hashCode ^
      name.hashCode ^
      delta.hashCode ^
      argumentsJson.hashCode ^
      outputPreview.hashCode ^
      ok.hashCode ^
      stopReason.hashCode ^
      message.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      resumedOps.hashCode ^
      recentlyActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentUiEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          operationId == other.operationId &&
          callId == other.callId &&
          name == other.name &&
          delta == other.delta &&
          argumentsJson == other.argumentsJson &&
          outputPreview == other.outputPreview &&
          ok == other.ok &&
          stopReason == other.stopReason &&
          message == other.message &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          resumedOps == other.resumedOps &&
          recentlyActive == other.recentlyActive;
}

class ResumeReport {
  final List<String> resumedOps;
  final List<String> statuses;

  const ResumeReport({required this.resumedOps, required this.statuses});

  @override
  int get hashCode => resumedOps.hashCode ^ statuses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResumeReport &&
          runtimeType == other.runtimeType &&
          resumedOps == other.resumedOps &&
          statuses == other.statuses;
}

class SessionSnapshot {
  final bool busy;
  final String lastOperationId;
  final String phase;
  final List<String> pendingCallIds;

  const SessionSnapshot({
    required this.busy,
    required this.lastOperationId,
    required this.phase,
    required this.pendingCallIds,
  });

  @override
  int get hashCode =>
      busy.hashCode ^
      lastOperationId.hashCode ^
      phase.hashCode ^
      pendingCallIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSnapshot &&
          runtimeType == other.runtimeType &&
          busy == other.busy &&
          lastOperationId == other.lastOperationId &&
          phase == other.phase &&
          pendingCallIds == other.pendingCallIds;
}
