// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_keep_scripted`, `aborted`, `base`, `build_harness`, `build_llm`, `build_tools`, `completed`, `demo_script_after_tool`, `demo_script_text`, `demo_script_tool`, `failed`, `map_resume`, `map_stream_event`, `operation_started`, `preview`, `session_ready`, `sqlite_url`, `text_delta`, `tool_args`, `tool_finished`, `tool_result`, `tool_started`, `usage`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EchoTool`, `RefillingScripted`, `Shared`, `TeeingEffects`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `call_tool`, `call`, `clone`, `complete_llm`, `description`, `name`, `parameters_schema`, `stream`

Future<AgentSession> sessionOpen({
  required String sqlitePath,
  required String projectRoot,
  required SessionOpenOpts opts,
}) => AgentRustLib.instance.api.crateApiSessionSessionOpen(
  sqlitePath: sqlitePath,
  projectRoot: projectRoot,
  opts: opts,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AgentSession>>
abstract class AgentSession implements RustOpaqueInterface {
  Future<void> abort();

  Future<void> close();

  Stream<AgentUiEvent> listen();

  Future<String> prompt({required String text});

  /// Rebuild harness/client; SQLite session tree is preserved.
  Future<void> reconfigure({required SessionOpenOpts opts});

  Future<ResumeReportDto> resume();

  SessionSnapshotDto snapshot();
}

/// Flat UI event (same shape as IM KimSessionEvent — avoids freezed enums).
class AgentUiEvent {
  final String kind;
  final String operationId;
  final String callId;
  final String name;
  final String delta;
  final String argumentsJson;
  final String outputPreview;
  final bool ok;
  final String stopReason;
  final String message;
  final BigInt inputTokens;
  final BigInt outputTokens;
  final List<String> resumedOps;

  const AgentUiEvent({
    required this.kind,
    required this.operationId,
    required this.callId,
    required this.name,
    required this.delta,
    required this.argumentsJson,
    required this.outputPreview,
    required this.ok,
    required this.stopReason,
    required this.message,
    required this.inputTokens,
    required this.outputTokens,
    required this.resumedOps,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      operationId.hashCode ^
      callId.hashCode ^
      name.hashCode ^
      delta.hashCode ^
      argumentsJson.hashCode ^
      outputPreview.hashCode ^
      ok.hashCode ^
      stopReason.hashCode ^
      message.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      resumedOps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentUiEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          operationId == other.operationId &&
          callId == other.callId &&
          name == other.name &&
          delta == other.delta &&
          argumentsJson == other.argumentsJson &&
          outputPreview == other.outputPreview &&
          ok == other.ok &&
          stopReason == other.stopReason &&
          message == other.message &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          resumedOps == other.resumedOps;
}

class ResumeReportDto {
  final List<String> resumedOps;
  final List<String> statuses;

  const ResumeReportDto({required this.resumedOps, required this.statuses});

  @override
  int get hashCode => resumedOps.hashCode ^ statuses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResumeReportDto &&
          runtimeType == other.runtimeType &&
          resumedOps == other.resumedOps &&
          statuses == other.statuses;
}

/// `llm_backend`: "scripted" | "responses_http"
class SessionOpenOpts {
  final String model;
  final String llmBackend;
  final bool resumeOnOpen;
  final String baseUrl;
  final String apiKey;
  final bool enableFsTools;
  final bool bashEnabled;

  const SessionOpenOpts({
    required this.model,
    required this.llmBackend,
    required this.resumeOnOpen,
    required this.baseUrl,
    required this.apiKey,
    required this.enableFsTools,
    required this.bashEnabled,
  });

  static Future<SessionOpenOpts> default_() =>
      AgentRustLib.instance.api.crateApiSessionSessionOpenOptsDefault();

  @override
  int get hashCode =>
      model.hashCode ^
      llmBackend.hashCode ^
      resumeOnOpen.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      enableFsTools.hashCode ^
      bashEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionOpenOpts &&
          runtimeType == other.runtimeType &&
          model == other.model &&
          llmBackend == other.llmBackend &&
          resumeOnOpen == other.resumeOnOpen &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          enableFsTools == other.enableFsTools &&
          bashEnabled == other.bashEnabled;
}

class SessionSnapshotDto {
  final bool busy;
  final String lastOperationId;

  const SessionSnapshotDto({required this.busy, required this.lastOperationId});

  @override
  int get hashCode => busy.hashCode ^ lastOperationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSnapshotDto &&
          runtimeType == other.runtimeType &&
          busy == other.busy &&
          lastOperationId == other.lastOperationId;
}
