[package]
name = "kim_client_ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = { workspace = true }
kim-agent-codec = { workspace = true }
kim-client = { workspace = true }
kim-log = { workspace = true }
kim-sdk = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
kim-desktop-runtime = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
libc = "0.2"

[lints]
workspace = true
