syntax = "proto3";
package kim.pkt;

enum Flag {
  Request = 0;
  Response = 1;
  Push = 2;
}

enum Status {
  Success = 0;
  InvalidPacket = 1;
  CommandNotFound = 2;
  ServiceUnavailable = 3;
  SystemException = 99;

  InvalidPacketBody = 101;
  InvalidCommand = 103;
  Unauthorized = 105;
  NoDestination = 300;   // Header.dest empty
  SessionNotFound = 404;
}

message Meta {
  string key = 1;
  string value = 2;
}

message Header {
  string command = 1;
  string channelId = 2;
  uint32 sequence = 3;
  Flag flag = 4;
  Status status = 5;
  string dest = 6;
  uint32 bodyLength = 7;
  repeated Meta meta = 8;
}

message InnerHandshakeReq {
  string serviceId = 1;
}

message LoginReq {
  string token = 1;
}

message LoginResp {
  string channelId = 1;
}

message Session {
  string channelId = 1;
  string gateId = 2;
  string account = 3;
  string zone = 4;
  string isp = 5;
  string remoteIP = 6;
  string device = 7;
  string app = 8;
  repeated string tags = 9;
}

message KickoutNotify {
  string channelId = 1;
}

message MessageReq {
  int32 type = 1;
  string body = 2;
  string extra = 3;
}

message MessageResp {
  int64 messageId = 1;
  int64 sendTime = 2;
}

message MessagePush {
  int64 messageId = 1;
  int32 type = 2;
  string body = 3;
  string extra = 4;
  string sender = 5;
  int64 sendTime = 6;
}

message GroupCreateReq {
  string name = 1;
  string avatar = 2;
  string introduction = 3;
  string owner = 4;
  repeated string members = 5;
}

message GroupCreateResp {
  string groupId = 1;
}
