// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/auth.dart';
import 'api/client.dart';
import 'api/simple.dart';
import 'api/types.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_KimAuthPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_KimUiHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  KimAuth
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    dynamic raw,
  );

  @protected
  KimUiHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    dynamic raw,
  );

  @protected
  KimAuth
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    dynamic raw,
  );

  @protected
  KimUiHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    dynamic raw,
  );

  @protected
  KimAuth
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    dynamic raw,
  );

  @protected
  KimUiHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    dynamic raw,
  );

  @protected
  RustStreamSink<AgentRunRequestDto>
  dco_decode_StreamSink_agent_run_request_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<SessionSnapshotDto>
  dco_decode_StreamSink_session_snapshot_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<SessionUpdateDto> dco_decode_StreamSink_session_update_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TimelineUpdateDto>
  dco_decode_StreamSink_timeline_update_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<TokenPersistDto> dco_decode_StreamSink_token_persist_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentCardDto dco_decode_agent_card_dto(dynamic raw);

  @protected
  AgentProfileDto dco_decode_agent_profile_dto(dynamic raw);

  @protected
  AgentRunRequestDto dco_decode_agent_run_request_dto(dynamic raw);

  @protected
  AgentRunResultDto dco_decode_agent_run_result_dto(dynamic raw);

  @protected
  AgentTurnStateDto dco_decode_agent_turn_state_dto(dynamic raw);

  @protected
  AuthSession dco_decode_auth_session(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BotDto dco_decode_bot_dto(dynamic raw);

  @protected
  AgentCardDto dco_decode_box_autoadd_agent_card_dto(dynamic raw);

  @protected
  AgentProfileDto dco_decode_box_autoadd_agent_profile_dto(dynamic raw);

  @protected
  AgentRunResultDto dco_decode_box_autoadd_agent_run_result_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  KimOutgoingContent dco_decode_box_autoadd_kim_outgoing_content(dynamic raw);

  @protected
  LinkStateDto dco_decode_box_autoadd_link_state_dto(dynamic raw);

  @protected
  ThreadViewDto dco_decode_box_autoadd_thread_view_dto(dynamic raw);

  @protected
  TimelineDeltaDto dco_decode_box_autoadd_timeline_delta_dto(dynamic raw);

  @protected
  TimelineSnapshotDto dco_decode_box_autoadd_timeline_snapshot_dto(dynamic raw);

  @protected
  UiCommandDto dco_decode_box_autoadd_ui_command_dto(dynamic raw);

  @protected
  CommandAckDto dco_decode_command_ack_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KimBotPendingItem dco_decode_kim_bot_pending_item(dynamic raw);

  @protected
  KimCommandReceipt dco_decode_kim_command_receipt(dynamic raw);

  @protected
  KimOutgoingContent dco_decode_kim_outgoing_content(dynamic raw);

  @protected
  KimTalkResult dco_decode_kim_talk_result(dynamic raw);

  @protected
  LinkStateDto dco_decode_link_state_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AgentProfileDto> dco_decode_list_agent_profile_dto(dynamic raw);

  @protected
  List<KimBotPendingItem> dco_decode_list_kim_bot_pending_item(dynamic raw);

  @protected
  List<MessageViewDto> dco_decode_list_message_view_dto(dynamic raw);

  @protected
  List<PersonDto> dco_decode_list_person_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RoomMemberDto> dco_decode_list_room_member_dto(dynamic raw);

  @protected
  List<ThreadViewDto> dco_decode_list_thread_view_dto(dynamic raw);

  @protected
  LocalMediaDto dco_decode_local_media_dto(dynamic raw);

  @protected
  MessagePageDto dco_decode_message_page_dto(dynamic raw);

  @protected
  MessageViewDto dco_decode_message_view_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  PersonDto dco_decode_person_dto(dynamic raw);

  @protected
  ProfileDto dco_decode_profile_dto(dynamic raw);

  @protected
  RoomMemberDto dco_decode_room_member_dto(dynamic raw);

  @protected
  SdkErrorDto dco_decode_sdk_error_dto(dynamic raw);

  @protected
  SendStatusDto dco_decode_send_status_dto(dynamic raw);

  @protected
  SessionSnapshotDto dco_decode_session_snapshot_dto(dynamic raw);

  @protected
  SessionUpdateDto dco_decode_session_update_dto(dynamic raw);

  @protected
  SettingsDto dco_decode_settings_dto(dynamic raw);

  @protected
  ThreadViewDto dco_decode_thread_view_dto(dynamic raw);

  @protected
  TimelineDeltaDto dco_decode_timeline_delta_dto(dynamic raw);

  @protected
  TimelineSnapshotDto dco_decode_timeline_snapshot_dto(dynamic raw);

  @protected
  TimelineUpdateDto dco_decode_timeline_update_dto(dynamic raw);

  @protected
  TokenPersistDto dco_decode_token_persist_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiCommandDto dco_decode_ui_command_dto(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  KimAuth
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    SseDeserializer deserializer,
  );

  @protected
  KimUiHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    SseDeserializer deserializer,
  );

  @protected
  KimAuth
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    SseDeserializer deserializer,
  );

  @protected
  KimUiHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    SseDeserializer deserializer,
  );

  @protected
  KimAuth
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    SseDeserializer deserializer,
  );

  @protected
  KimUiHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AgentRunRequestDto>
  sse_decode_StreamSink_agent_run_request_dto_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<SessionSnapshotDto>
  sse_decode_StreamSink_session_snapshot_dto_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<SessionUpdateDto> sse_decode_StreamSink_session_update_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TimelineUpdateDto>
  sse_decode_StreamSink_timeline_update_dto_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<TokenPersistDto> sse_decode_StreamSink_token_persist_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentCardDto sse_decode_agent_card_dto(SseDeserializer deserializer);

  @protected
  AgentProfileDto sse_decode_agent_profile_dto(SseDeserializer deserializer);

  @protected
  AgentRunRequestDto sse_decode_agent_run_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  AgentRunResultDto sse_decode_agent_run_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  AgentTurnStateDto sse_decode_agent_turn_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  AuthSession sse_decode_auth_session(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BotDto sse_decode_bot_dto(SseDeserializer deserializer);

  @protected
  AgentCardDto sse_decode_box_autoadd_agent_card_dto(
    SseDeserializer deserializer,
  );

  @protected
  AgentProfileDto sse_decode_box_autoadd_agent_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  AgentRunResultDto sse_decode_box_autoadd_agent_run_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  KimOutgoingContent sse_decode_box_autoadd_kim_outgoing_content(
    SseDeserializer deserializer,
  );

  @protected
  LinkStateDto sse_decode_box_autoadd_link_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  ThreadViewDto sse_decode_box_autoadd_thread_view_dto(
    SseDeserializer deserializer,
  );

  @protected
  TimelineDeltaDto sse_decode_box_autoadd_timeline_delta_dto(
    SseDeserializer deserializer,
  );

  @protected
  TimelineSnapshotDto sse_decode_box_autoadd_timeline_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  UiCommandDto sse_decode_box_autoadd_ui_command_dto(
    SseDeserializer deserializer,
  );

  @protected
  CommandAckDto sse_decode_command_ack_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KimBotPendingItem sse_decode_kim_bot_pending_item(
    SseDeserializer deserializer,
  );

  @protected
  KimCommandReceipt sse_decode_kim_command_receipt(
    SseDeserializer deserializer,
  );

  @protected
  KimOutgoingContent sse_decode_kim_outgoing_content(
    SseDeserializer deserializer,
  );

  @protected
  KimTalkResult sse_decode_kim_talk_result(SseDeserializer deserializer);

  @protected
  LinkStateDto sse_decode_link_state_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AgentProfileDto> sse_decode_list_agent_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<KimBotPendingItem> sse_decode_list_kim_bot_pending_item(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageViewDto> sse_decode_list_message_view_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PersonDto> sse_decode_list_person_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RoomMemberDto> sse_decode_list_room_member_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ThreadViewDto> sse_decode_list_thread_view_dto(
    SseDeserializer deserializer,
  );

  @protected
  LocalMediaDto sse_decode_local_media_dto(SseDeserializer deserializer);

  @protected
  MessagePageDto sse_decode_message_page_dto(SseDeserializer deserializer);

  @protected
  MessageViewDto sse_decode_message_view_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PersonDto sse_decode_person_dto(SseDeserializer deserializer);

  @protected
  ProfileDto sse_decode_profile_dto(SseDeserializer deserializer);

  @protected
  RoomMemberDto sse_decode_room_member_dto(SseDeserializer deserializer);

  @protected
  SdkErrorDto sse_decode_sdk_error_dto(SseDeserializer deserializer);

  @protected
  SendStatusDto sse_decode_send_status_dto(SseDeserializer deserializer);

  @protected
  SessionSnapshotDto sse_decode_session_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionUpdateDto sse_decode_session_update_dto(SseDeserializer deserializer);

  @protected
  SettingsDto sse_decode_settings_dto(SseDeserializer deserializer);

  @protected
  ThreadViewDto sse_decode_thread_view_dto(SseDeserializer deserializer);

  @protected
  TimelineDeltaDto sse_decode_timeline_delta_dto(SseDeserializer deserializer);

  @protected
  TimelineSnapshotDto sse_decode_timeline_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  TimelineUpdateDto sse_decode_timeline_update_dto(
    SseDeserializer deserializer,
  );

  @protected
  TokenPersistDto sse_decode_token_persist_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiCommandDto sse_decode_ui_command_dto(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    KimAuth self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    KimUiHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    KimAuth self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    KimUiHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    KimAuth self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    KimUiHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_agent_run_request_dto_Sse(
    RustStreamSink<AgentRunRequestDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_session_snapshot_dto_Sse(
    RustStreamSink<SessionSnapshotDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_session_update_dto_Sse(
    RustStreamSink<SessionUpdateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_timeline_update_dto_Sse(
    RustStreamSink<TimelineUpdateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_token_persist_dto_Sse(
    RustStreamSink<TokenPersistDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_card_dto(AgentCardDto self, SseSerializer serializer);

  @protected
  void sse_encode_agent_profile_dto(
    AgentProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_run_request_dto(
    AgentRunRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_run_result_dto(
    AgentRunResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_turn_state_dto(
    AgentTurnStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_auth_session(AuthSession self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bot_dto(BotDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_agent_card_dto(
    AgentCardDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_agent_profile_dto(
    AgentProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_agent_run_result_dto(
    AgentRunResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_kim_outgoing_content(
    KimOutgoingContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_link_state_dto(
    LinkStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thread_view_dto(
    ThreadViewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_timeline_delta_dto(
    TimelineDeltaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_timeline_snapshot_dto(
    TimelineSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_command_dto(
    UiCommandDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_command_ack_dto(CommandAckDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_kim_bot_pending_item(
    KimBotPendingItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_kim_command_receipt(
    KimCommandReceipt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_kim_outgoing_content(
    KimOutgoingContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_kim_talk_result(KimTalkResult self, SseSerializer serializer);

  @protected
  void sse_encode_link_state_dto(LinkStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_agent_profile_dto(
    List<AgentProfileDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_kim_bot_pending_item(
    List<KimBotPendingItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_view_dto(
    List<MessageViewDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_person_dto(
    List<PersonDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_room_member_dto(
    List<RoomMemberDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_thread_view_dto(
    List<ThreadViewDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_media_dto(LocalMediaDto self, SseSerializer serializer);

  @protected
  void sse_encode_message_page_dto(
    MessagePageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_view_dto(
    MessageViewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_person_dto(PersonDto self, SseSerializer serializer);

  @protected
  void sse_encode_profile_dto(ProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_room_member_dto(RoomMemberDto self, SseSerializer serializer);

  @protected
  void sse_encode_sdk_error_dto(SdkErrorDto self, SseSerializer serializer);

  @protected
  void sse_encode_send_status_dto(SendStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_session_snapshot_dto(
    SessionSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_update_dto(
    SessionUpdateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_dto(SettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_thread_view_dto(ThreadViewDto self, SseSerializer serializer);

  @protected
  void sse_encode_timeline_delta_dto(
    TimelineDeltaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_snapshot_dto(
    TimelineSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_update_dto(
    TimelineUpdateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_token_persist_dto(
    TokenPersistDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_command_dto(UiCommandDto self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimUiHandle(
    int ptr,
  );
}
