// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth.dart';
import 'api/client.dart';
import 'api/simple.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1563396908;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'kim_client_ffi',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiClientKimApiAck({
    required KimApi that,
    required PlatformInt64 messageId,
  });

  Future<String> crateApiClientKimApiConnect({required KimApi that});

  Future<String> crateApiClientKimApiDisconnect({required KimApi that});

  Future<String> crateApiClientKimApiFriendAccept({
    required KimApi that,
    required String dest,
  });

  Future<String> crateApiClientKimApiFriendIncoming({required KimApi that});

  Future<String> crateApiClientKimApiFriendList({required KimApi that});

  Future<String> crateApiClientKimApiFriendReject({
    required KimApi that,
    required String dest,
  });

  Future<String> crateApiClientKimApiFriendRequest({
    required KimApi that,
    required String dest,
  });

  Stream<KimPush> crateApiClientKimApiListen({required KimApi that});

  Future<String> crateApiClientKimApiLogin({required KimApi that});

  KimApi crateApiClientKimApiNew({
    required String url,
    required String token,
    required String userAgent,
  });

  Future<String> crateApiClientKimApiPing({required KimApi that});

  Future<String> crateApiClientKimApiSearchUsers({
    required KimApi that,
    required String query,
  });

  Future<String> crateApiClientKimApiTalkToUser({
    required KimApi that,
    required String dest,
    required String body,
  });

  Future<void> crateApiAuthKimAuthChangePassword({
    required KimAuth that,
    required String token,
    required String oldPassword,
    required String newPassword,
  });

  Future<AuthSession> crateApiAuthKimAuthLogin({
    required KimAuth that,
    required String account,
    required String password,
  });

  Future<void> crateApiAuthKimAuthLogout({
    required KimAuth that,
    required String token,
  });

  KimAuth crateApiAuthKimAuthNew({
    required String baseUrl,
    required String userAgent,
  });

  Future<AuthSession> crateApiAuthKimAuthRegister({
    required KimAuth that,
    required String account,
    required String password,
  });

  String crateApiSimpleGreet({required String name});

  String crateApiAuthHttpOriginFromWs({required String wsUrl});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_KimApi;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_KimApi;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_KimApiPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_KimAuth;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_KimAuth;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_KimAuthPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiClientKimApiAck({
    required KimApi that,
    required PlatformInt64 messageId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          sse_encode_i_64(messageId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiAckConstMeta,
        argValues: [that, messageId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiAckConstMeta => const TaskConstMeta(
    debugName: "KimApi_ack",
    argNames: ["that", "messageId"],
  );

  @override
  Future<String> crateApiClientKimApiConnect({required KimApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiConnectConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiConnectConstMeta =>
      const TaskConstMeta(debugName: "KimApi_connect", argNames: ["that"]);

  @override
  Future<String> crateApiClientKimApiDisconnect({required KimApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiDisconnectConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiDisconnectConstMeta =>
      const TaskConstMeta(debugName: "KimApi_disconnect", argNames: ["that"]);

  @override
  Future<String> crateApiClientKimApiFriendAccept({
    required KimApi that,
    required String dest,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          sse_encode_String(dest, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiFriendAcceptConstMeta,
        argValues: [that, dest],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiFriendAcceptConstMeta =>
      const TaskConstMeta(
        debugName: "KimApi_friend_accept",
        argNames: ["that", "dest"],
      );

  @override
  Future<String> crateApiClientKimApiFriendIncoming({required KimApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiFriendIncomingConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiFriendIncomingConstMeta =>
      const TaskConstMeta(
        debugName: "KimApi_friend_incoming",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiClientKimApiFriendList({required KimApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiFriendListConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiFriendListConstMeta =>
      const TaskConstMeta(debugName: "KimApi_friend_list", argNames: ["that"]);

  @override
  Future<String> crateApiClientKimApiFriendReject({
    required KimApi that,
    required String dest,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          sse_encode_String(dest, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiFriendRejectConstMeta,
        argValues: [that, dest],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiFriendRejectConstMeta =>
      const TaskConstMeta(
        debugName: "KimApi_friend_reject",
        argNames: ["that", "dest"],
      );

  @override
  Future<String> crateApiClientKimApiFriendRequest({
    required KimApi that,
    required String dest,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          sse_encode_String(dest, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiFriendRequestConstMeta,
        argValues: [that, dest],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiFriendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "KimApi_friend_request",
        argNames: ["that", "dest"],
      );

  @override
  Stream<KimPush> crateApiClientKimApiListen({required KimApi that}) {
    final sink = RustStreamSink<KimPush>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          sse_encode_StreamSink_kim_push_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiListenConstMeta,
        argValues: [that, sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiClientKimApiListenConstMeta => const TaskConstMeta(
    debugName: "KimApi_listen",
    argNames: ["that", "sink"],
  );

  @override
  Future<String> crateApiClientKimApiLogin({required KimApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiLoginConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiLoginConstMeta =>
      const TaskConstMeta(debugName: "KimApi_login", argNames: ["that"]);

  @override
  KimApi crateApiClientKimApiNew({
    required String url,
    required String token,
    required String userAgent,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(token, serializer);
          sse_encode_String(userAgent, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientKimApiNewConstMeta,
        argValues: [url, token, userAgent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiNewConstMeta => const TaskConstMeta(
    debugName: "KimApi_new",
    argNames: ["url", "token", "userAgent"],
  );

  @override
  Future<String> crateApiClientKimApiPing({required KimApi that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiPingConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiPingConstMeta =>
      const TaskConstMeta(debugName: "KimApi_ping", argNames: ["that"]);

  @override
  Future<String> crateApiClientKimApiSearchUsers({
    required KimApi that,
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiSearchUsersConstMeta,
        argValues: [that, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiSearchUsersConstMeta =>
      const TaskConstMeta(
        debugName: "KimApi_search_users",
        argNames: ["that", "query"],
      );

  @override
  Future<String> crateApiClientKimApiTalkToUser({
    required KimApi that,
    required String dest,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
            that,
            serializer,
          );
          sse_encode_String(dest, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientKimApiTalkToUserConstMeta,
        argValues: [that, dest, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientKimApiTalkToUserConstMeta =>
      const TaskConstMeta(
        debugName: "KimApi_talk_to_user",
        argNames: ["that", "dest", "body"],
      );

  @override
  Future<void> crateApiAuthKimAuthChangePassword({
    required KimAuth that,
    required String token,
    required String oldPassword,
    required String newPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
            that,
            serializer,
          );
          sse_encode_String(token, serializer);
          sse_encode_String(oldPassword, serializer);
          sse_encode_String(newPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthKimAuthChangePasswordConstMeta,
        argValues: [that, token, oldPassword, newPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthKimAuthChangePasswordConstMeta =>
      const TaskConstMeta(
        debugName: "KimAuth_change_password",
        argNames: ["that", "token", "oldPassword", "newPassword"],
      );

  @override
  Future<AuthSession> crateApiAuthKimAuthLogin({
    required KimAuth that,
    required String account,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
            that,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_session,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthKimAuthLoginConstMeta,
        argValues: [that, account, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthKimAuthLoginConstMeta => const TaskConstMeta(
    debugName: "KimAuth_login",
    argNames: ["that", "account", "password"],
  );

  @override
  Future<void> crateApiAuthKimAuthLogout({
    required KimAuth that,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
            that,
            serializer,
          );
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthKimAuthLogoutConstMeta,
        argValues: [that, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthKimAuthLogoutConstMeta => const TaskConstMeta(
    debugName: "KimAuth_logout",
    argNames: ["that", "token"],
  );

  @override
  KimAuth crateApiAuthKimAuthNew({
    required String baseUrl,
    required String userAgent,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(userAgent, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthKimAuthNewConstMeta,
        argValues: [baseUrl, userAgent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthKimAuthNewConstMeta => const TaskConstMeta(
    debugName: "KimAuth_new",
    argNames: ["baseUrl", "userAgent"],
  );

  @override
  Future<AuthSession> crateApiAuthKimAuthRegister({
    required KimAuth that,
    required String account,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
            that,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_session,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthKimAuthRegisterConstMeta,
        argValues: [that, account, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthKimAuthRegisterConstMeta =>
      const TaskConstMeta(
        debugName: "KimAuth_register",
        argNames: ["that", "account", "password"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  String crateApiAuthHttpOriginFromWs({required String wsUrl}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wsUrl, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAuthHttpOriginFromWsConstMeta,
        argValues: [wsUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthHttpOriginFromWsConstMeta =>
      const TaskConstMeta(
        debugName: "http_origin_from_ws",
        argNames: ["wsUrl"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_KimApi => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_KimApi => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_KimAuth => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_KimAuth => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  KimApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KimApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KimAuth
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KimAuthImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KimApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KimApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KimAuth
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KimAuthImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KimApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KimApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KimAuth
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KimAuthImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<KimPush> dco_decode_StreamSink_kim_push_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthSession dco_decode_auth_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AuthSession(
      token: dco_decode_String(arr[0]),
      exp: dco_decode_i_64(arr[1]),
      account: dco_decode_String(arr[2]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  KimPush dco_decode_kim_push(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return KimPush(
      kind: dco_decode_String(arr[0]),
      dest: dco_decode_String(arr[1]),
      sender: dco_decode_String(arr[2]),
      body: dco_decode_String(arr[3]),
      extra: dco_decode_String(arr[4]),
      messageId: dco_decode_i_64(arr[5]),
      sendTime: dco_decode_i_64(arr[6]),
      token: dco_decode_String(arr[7]),
      exp: dco_decode_i_64(arr[8]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  KimApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KimApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KimAuth
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KimAuthImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KimApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KimApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KimAuth
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KimAuthImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KimApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KimApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KimAuth
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KimAuthImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<KimPush> sse_decode_StreamSink_kim_push_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthSession sse_decode_auth_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_token = sse_decode_String(deserializer);
    var var_exp = sse_decode_i_64(deserializer);
    var var_account = sse_decode_String(deserializer);
    return AuthSession(token: var_token, exp: var_exp, account: var_account);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  KimPush sse_decode_kim_push(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_dest = sse_decode_String(deserializer);
    var var_sender = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_extra = sse_decode_String(deserializer);
    var var_messageId = sse_decode_i_64(deserializer);
    var var_sendTime = sse_decode_i_64(deserializer);
    var var_token = sse_decode_String(deserializer);
    var var_exp = sse_decode_i_64(deserializer);
    return KimPush(
      kind: var_kind,
      dest: var_dest,
      sender: var_sender,
      body: var_body,
      extra: var_extra,
      messageId: var_messageId,
      sendTime: var_sendTime,
      token: var_token,
      exp: var_exp,
    );
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
    KimApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KimApiImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    KimAuth self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KimAuthImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
    KimApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KimApiImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    KimAuth self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KimAuthImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimApi(
    KimApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KimApiImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKimAuth(
    KimAuth self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KimAuthImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_kim_push_Sse(
    RustStreamSink<KimPush> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_kim_push,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_session(AuthSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.token, serializer);
    sse_encode_i_64(self.exp, serializer);
    sse_encode_String(self.account, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_kim_push(KimPush self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.dest, serializer);
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.extra, serializer);
    sse_encode_i_64(self.messageId, serializer);
    sse_encode_i_64(self.sendTime, serializer);
    sse_encode_String(self.token, serializer);
    sse_encode_i_64(self.exp, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class KimApiImpl extends RustOpaque implements KimApi {
  // Not to be used by end users
  KimApiImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  KimApiImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_KimApi,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_KimApi,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_KimApiPtr,
  );

  Future<String> ack({required PlatformInt64 messageId}) => RustLib.instance.api
      .crateApiClientKimApiAck(that: this, messageId: messageId);

  Future<String> connect() =>
      RustLib.instance.api.crateApiClientKimApiConnect(that: this);

  Future<String> disconnect() =>
      RustLib.instance.api.crateApiClientKimApiDisconnect(that: this);

  Future<String> friendAccept({required String dest}) => RustLib.instance.api
      .crateApiClientKimApiFriendAccept(that: this, dest: dest);

  Future<String> friendIncoming() =>
      RustLib.instance.api.crateApiClientKimApiFriendIncoming(that: this);

  Future<String> friendList() =>
      RustLib.instance.api.crateApiClientKimApiFriendList(that: this);

  Future<String> friendReject({required String dest}) => RustLib.instance.api
      .crateApiClientKimApiFriendReject(that: this, dest: dest);

  Future<String> friendRequest({required String dest}) => RustLib.instance.api
      .crateApiClientKimApiFriendRequest(that: this, dest: dest);

  /// Unsolicited events after login. Does not hold the talk path.
  Stream<KimPush> listen() =>
      RustLib.instance.api.crateApiClientKimApiListen(that: this);

  Future<String> login() =>
      RustLib.instance.api.crateApiClientKimApiLogin(that: this);

  Future<String> ping() =>
      RustLib.instance.api.crateApiClientKimApiPing(that: this);

  Future<String> searchUsers({required String query}) => RustLib.instance.api
      .crateApiClientKimApiSearchUsers(that: this, query: query);

  Future<String> talkToUser({required String dest, required String body}) =>
      RustLib.instance.api.crateApiClientKimApiTalkToUser(
        that: this,
        dest: dest,
        body: body,
      );
}

@sealed
class KimAuthImpl extends RustOpaque implements KimAuth {
  // Not to be used by end users
  KimAuthImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  KimAuthImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_KimAuth,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_KimAuth,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_KimAuthPtr,
  );

  Future<void> changePassword({
    required String token,
    required String oldPassword,
    required String newPassword,
  }) => RustLib.instance.api.crateApiAuthKimAuthChangePassword(
    that: this,
    token: token,
    oldPassword: oldPassword,
    newPassword: newPassword,
  );

  Future<AuthSession> login({
    required String account,
    required String password,
  }) => RustLib.instance.api.crateApiAuthKimAuthLogin(
    that: this,
    account: account,
    password: password,
  );

  Future<void> logout({required String token}) =>
      RustLib.instance.api.crateApiAuthKimAuthLogout(that: this, token: token);

  Future<AuthSession> register({
    required String account,
    required String password,
  }) => RustLib.instance.api.crateApiAuthKimAuthRegister(
    that: this,
    account: account,
    password: password,
  );
}
