export const COPY = {
  brand: "KIM",
  brandSub: "即时通讯",
  description: "KIM 即时通讯",

  loginTitle: "登录",
  registerTitle: "创建账号",
  account: "账号",
  password: "密码",
  confirmPassword: "确认密码",
  accountPlaceholder: "请输入账号",
  passwordPlaceholder: "请输入密码",
  confirmPlaceholder: "再次输入密码",
  accountHint: "3–32 位字母、数字或下划线",
  passwordHint: "8–128 位",
  showPassword: "显示密码",
  hidePassword: "隐藏密码",
  loginAction: "登录",
  registerAction: "注册",
  submittingLogin: "登录中…",
  submittingRegister: "注册中…",
  noAccount: "没有账号？",
  goRegister: "注册",
  hasAccount: "已有账号？",
  goLogin: "登录",
  mismatch: "两次输入的密码不一致",
  invalidAccount: "账号需为 3–32 位字母、数字或下划线",
  invalidPassword: "密码需为 8–128 位",
  badCredentials: "账号或密码错误",
  accountExists: "账号已存在",
  network: "网络异常，请稍后重试",
  unavailable: "服务暂时不可用，请稍后重试",
  authFailed: "登录失败，请稍后重试",
  wsFailed: "连接未建立，请重试",
  timeout: "连接超时，请稍后重试",
  required: "请填写完整信息",

  conversations: "会话",
  searchPlaceholder: "搜索会话",
  newChat: "新对话",
  newGroup: "新建群组",
  startChat: "开始对话",
  noConversations: "暂无会话",
  noConversationsHint: "添加好友后，从通讯录开始聊天",
  noMatch: "没有匹配的会话",
  pickConversation: "选择一个会话",
  pickConversationHint: "从左侧打开会话，或在通讯录里选一位好友",
  noMessages: "还没有消息",
  messagePlaceholder: "输入消息",
  send: "发送",
  sendFailed: "发送失败",
  notConnected: "尚未连接",
  retry: "重试",

  peerAccount: "对方账号",
  peerPlaceholder: "输入对方账号",
  cannotChatSelf: "不能选择自己的账号",
  openChat: "开始",

  groupName: "群名称",
  groupNamePlaceholder: "输入群名称",
  groupMembers: "成员",
  memberPlaceholder: "输入成员账号后添加",
  addMember: "添加",
  createGroup: "创建",
  creating: "创建中…",
  cancel: "取消",
  groupCreated: "群组已创建",
  members: "成员",
  privateChat: "私聊",
  groupChat: "群聊",
  back: "返回",
  close: "关闭",
  you: "你",

  online: "在线",
  connecting: "连接中",
  reconnecting: "重连中",
  offline: "已断开",
  kicked: "账号已在其他设备登录",
  logout: "退出登录",
  yesterday: "昨天",

  profile: "个人资料",
  nickname: "昵称",
  bio: "简介",
  saveProfile: "保存",
  saved: "已保存",
  changePassword: "修改密码",
  oldPassword: "当前密码",
  newPassword: "新密码",
  passwordChanged: "密码已更新",

  contacts: "通讯录",
  addFriend: "添加好友",
  searchPeople: "搜索账号或昵称",
  requestSent: "已发送好友申请",
  incoming: "新的朋友",
  friendRequestToast: "发来好友申请",
  accept: "同意",
  reject: "拒绝",
  noFriends: "还没有好友",
  noFriendsHint: "搜索账号，发送好友申请",
  noIncoming: "暂无好友申请",
  notFriends: "对方还不是你好友",
  blocked: "无法与该用户互动",
  friendAccepted: "已成为好友",
  userNotFound: "找不到该用户",
  cannotAddSelf: "不能添加自己",
  waitingAccept: "已发送申请，通过后即可聊天",
  addFriendToChat: "加为好友后即可发送消息",
  requested: "已申请",
  chatAction: "发消息",
  searchEmpty: "没有找到相关用户",
  pickFriends: "从通讯录选择成员",
};

export function memberCount(n: number): string {
  return `${n} 位成员`;
}
