rule_files:
  - /etc/prometheus/rules/kim.yml

scrape_configs:
  - job_name: gateway
    scrape_interval: 5s
    static_configs:
      - targets: ["gateway:9001"]
  - job_name: chat
    scrape_interval: 5s
    static_configs:
      - targets: ["chat:9002", "chat-gray:9002"]
  - job_name: royal
    scrape_interval: 5s
    static_configs:
      - targets: ["royal:9003", "royal-2:9003"]
  - job_name: router
    scrape_interval: 5s
    static_configs:
      - targets: ["router:8088"]
