// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1511956223;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__catalog__capability_catalog_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "capability_catalog",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::catalog::capability_catalog())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__catalog__catalog_surface_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "catalog_surface",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_vendor = <String>::sse_decode(&mut deserializer);
            let api_model = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::failure::AgentFailure>((move || {
                    let output_ok = crate::api::catalog::catalog_surface(api_vendor, api_model)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__catalog__catalog_validate_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "catalog_validate",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_vendor = <String>::sse_decode(&mut deserializer);
            let api_model = <String>::sse_decode(&mut deserializer);
            let api_choice_kind = <String>::sse_decode(&mut deserializer);
            let api_on = <bool>::sse_decode(&mut deserializer);
            let api_value = <String>::sse_decode(&mut deserializer);
            let api_budget = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::failure::AgentFailure>((move || {
                    let output_ok = crate::api::catalog::catalog_validate(
                        api_vendor,
                        api_model,
                        api_choice_kind,
                        api_on,
                        api_value,
                        api_budget,
                    )?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__catalog__catalog_vendors_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "catalog_vendors",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::failure::AgentFailure>((move || {
                    let output_ok = crate::api::catalog::catalog_vendors()?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__session__fetch_supported_models_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_supported_models",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_llm_backend = <String>::sse_decode(&mut deserializer);
            let api_base_url = <String>::sse_decode(&mut deserializer);
            let api_api_key = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::failure::AgentFailure>(
                    (move || async move {
                        let output_ok = crate::api::session::fetch_supported_models(
                            api_llm_backend,
                            api_base_url,
                            api_api_key,
                        )
                        .await?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::simple::init_app();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__session__list_builtin_profiles_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_builtin_profiles",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::failure::AgentFailure>((move || {
                    let output_ok = crate::api::session::list_builtin_profiles()?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__session__list_bundled_providers_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_bundled_providers",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::session::list_bundled_providers())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__catalog__preview_assembled_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "preview_assembled",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_profile_json = <String>::sse_decode(&mut deserializer);
            let api_project_root = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::failure::AgentFailure>((move || {
                    let output_ok =
                        crate::api::catalog::preview_assembled(api_profile_json, api_project_root)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__catalog__skill_app_catalog_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "skill_app_catalog",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_cache_root = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Ok::<_, ()>(crate::api::catalog::skill_app_catalog(api_cache_root))?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__catalog__skill_portable_list_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "skill_portable_list",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_user_root = <String>::sse_decode(&mut deserializer);
            let api_project_root = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::catalog::skill_portable_list(
                        api_user_root,
                        api_project_root,
                    ))?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::failure::AgentFailure {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::failure::AgentFailure::MissingApiKey;
            }
            1 => {
                let mut var_name = <String>::sse_decode(deserializer);
                return crate::api::failure::AgentFailure::UnknownProvider { name: var_name };
            }
            2 => {
                return crate::api::failure::AgentFailure::InvalidUrl;
            }
            3 => {
                return crate::api::failure::AgentFailure::Busy;
            }
            4 => {
                return crate::api::failure::AgentFailure::UnknownSession;
            }
            5 => {
                return crate::api::failure::AgentFailure::UnknownToolCall;
            }
            6 => {
                return crate::api::failure::AgentFailure::RateLimited;
            }
            7 => {
                return crate::api::failure::AgentFailure::ContextExceeded;
            }
            8 => {
                let mut var_recentlyActive = <bool>::sse_decode(deserializer);
                return crate::api::failure::AgentFailure::Poisoned {
                    recently_active: var_recentlyActive,
                };
            }
            9 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::failure::AgentFailure::Failed {
                    message: var_message,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::session::AgentUiEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_operationId = <String>::sse_decode(deserializer);
        let mut var_callId = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_delta = <String>::sse_decode(deserializer);
        let mut var_argumentsJson = <String>::sse_decode(deserializer);
        let mut var_outputPreview = <String>::sse_decode(deserializer);
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_stopReason = <String>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_inputTokens = <u64>::sse_decode(deserializer);
        let mut var_outputTokens = <u64>::sse_decode(deserializer);
        let mut var_resumedOps = <Vec<String>>::sse_decode(deserializer);
        let mut var_recentlyActive = <bool>::sse_decode(deserializer);
        return crate::api::session::AgentUiEvent {
            kind: var_kind,
            operation_id: var_operationId,
            call_id: var_callId,
            name: var_name,
            delta: var_delta,
            arguments_json: var_argumentsJson,
            output_preview: var_outputPreview,
            ok: var_ok,
            stop_reason: var_stopReason,
            message: var_message,
            input_tokens: var_inputTokens,
            output_tokens: var_outputTokens,
            resumed_ops: var_resumedOps,
            recently_active: var_recentlyActive,
        };
    }
}

impl SseDecode for crate::api::catalog::AssembledPreview {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_tools = <Vec<crate::api::catalog::PreviewTool>>::sse_decode(deserializer);
        let mut var_warnings = <Vec<String>>::sse_decode(deserializer);
        return crate::api::catalog::AssembledPreview {
            tools: var_tools,
            warnings: var_warnings,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::catalog::CapabilityEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_risk = <String>::sse_decode(deserializer);
        return crate::api::catalog::CapabilityEntry {
            kind: var_kind,
            risk: var_risk,
        };
    }
}

impl SseDecode for crate::api::catalog::CatalogValidate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_on_ = <bool>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        let mut var_budget = <u32>::sse_decode(deserializer);
        let mut var_dropped = <Vec<String>>::sse_decode(deserializer);
        return crate::api::catalog::CatalogValidate {
            kind: var_kind,
            on: var_on_,
            value: var_value,
            budget: var_budget,
            dropped: var_dropped,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::catalog::CapabilityEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::catalog::CapabilityEntry>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::catalog::PreviewTool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::catalog::PreviewTool>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::catalog::Skill> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::catalog::Skill>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::catalog::Vendor> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::catalog::Vendor>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::catalog::PreviewTool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_source = <String>::sse_decode(deserializer);
        let mut var_executor = <String>::sse_decode(deserializer);
        return crate::api::catalog::PreviewTool {
            name: var_name,
            source: var_source,
            executor: var_executor,
        };
    }
}

impl SseDecode for crate::api::catalog::ReasoningSurface {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_note = <String>::sse_decode(deserializer);
        let mut var_param = <String>::sse_decode(deserializer);
        let mut var_defaultOn = <bool>::sse_decode(deserializer);
        let mut var_allowed = <Vec<String>>::sse_decode(deserializer);
        let mut var_defaultValue = <String>::sse_decode(deserializer);
        let mut var_min = <u32>::sse_decode(deserializer);
        let mut var_max = <u32>::sse_decode(deserializer);
        let mut var_defaultBudget = <u32>::sse_decode(deserializer);
        return crate::api::catalog::ReasoningSurface {
            kind: var_kind,
            note: var_note,
            param: var_param,
            default_on: var_defaultOn,
            allowed: var_allowed,
            default_value: var_defaultValue,
            min: var_min,
            max: var_max,
            default_budget: var_defaultBudget,
        };
    }
}

impl SseDecode for crate::api::session::ResumeReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_resumedOps = <Vec<String>>::sse_decode(deserializer);
        let mut var_statuses = <Vec<String>>::sse_decode(deserializer);
        return crate::api::session::ResumeReport {
            resumed_ops: var_resumedOps,
            statuses: var_statuses,
        };
    }
}

impl SseDecode for crate::api::session::SessionSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_busy = <bool>::sse_decode(deserializer);
        let mut var_lastOperationId = <String>::sse_decode(deserializer);
        let mut var_phase = <String>::sse_decode(deserializer);
        let mut var_pendingCallIds = <Vec<String>>::sse_decode(deserializer);
        return crate::api::session::SessionSnapshot {
            busy: var_busy,
            last_operation_id: var_lastOperationId,
            phase: var_phase,
            pending_call_ids: var_pendingCallIds,
        };
    }
}

impl SseDecode for crate::api::catalog::Skill {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_description = <String>::sse_decode(deserializer);
        let mut var_version = <String>::sse_decode(deserializer);
        let mut var_origin = <String>::sse_decode(deserializer);
        let mut var_className = <String>::sse_decode(deserializer);
        let mut var_dir = <String>::sse_decode(deserializer);
        return crate::api::catalog::Skill {
            id: var_id,
            name: var_name,
            description: var_description,
            version: var_version,
            origin: var_origin,
            class_name: var_className,
            dir: var_dir,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::catalog::Vendor {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_displayName = <String>::sse_decode(deserializer);
        let mut var_group = <String>::sse_decode(deserializer);
        let mut var_sortRank = <u32>::sse_decode(deserializer);
        let mut var_defaultBaseUrl = <String>::sse_decode(deserializer);
        let mut var_altBaseUrls = <Vec<String>>::sse_decode(deserializer);
        let mut var_dynamicModels = <bool>::sse_decode(deserializer);
        let mut var_customModel = <bool>::sse_decode(deserializer);
        let mut var_defaultModel = <String>::sse_decode(deserializer);
        let mut var_models = <Vec<String>>::sse_decode(deserializer);
        return crate::api::catalog::Vendor {
            id: var_id,
            display_name: var_displayName,
            group: var_group,
            sort_rank: var_sortRank,
            default_base_url: var_defaultBaseUrl,
            alt_base_urls: var_altBaseUrls,
            dynamic_models: var_dynamicModels,
            custom_model: var_customModel,
            default_model: var_defaultModel,
            models: var_models,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__catalog__capability_catalog_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__catalog__catalog_surface_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__catalog__catalog_validate_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__catalog__catalog_vendors_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__session__fetch_supported_models_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        6 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        7 => {
            wire__crate__api__session__list_builtin_profiles_impl(port, ptr, rust_vec_len, data_len)
        }
        8 => wire__crate__api__session__list_bundled_providers_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        9 => wire__crate__api__catalog__preview_assembled_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__catalog__skill_app_catalog_impl(port, ptr, rust_vec_len, data_len),
        11 => {
            wire__crate__api__catalog__skill_portable_list_impl(port, ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::failure::AgentFailure {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::failure::AgentFailure::MissingApiKey => [0.into_dart()].into_dart(),
            crate::api::failure::AgentFailure::UnknownProvider { name } => {
                [1.into_dart(), name.into_into_dart().into_dart()].into_dart()
            }
            crate::api::failure::AgentFailure::InvalidUrl => [2.into_dart()].into_dart(),
            crate::api::failure::AgentFailure::Busy => [3.into_dart()].into_dart(),
            crate::api::failure::AgentFailure::UnknownSession => [4.into_dart()].into_dart(),
            crate::api::failure::AgentFailure::UnknownToolCall => [5.into_dart()].into_dart(),
            crate::api::failure::AgentFailure::RateLimited => [6.into_dart()].into_dart(),
            crate::api::failure::AgentFailure::ContextExceeded => [7.into_dart()].into_dart(),
            crate::api::failure::AgentFailure::Poisoned { recently_active } => {
                [8.into_dart(), recently_active.into_into_dart().into_dart()].into_dart()
            }
            crate::api::failure::AgentFailure::Failed { message } => {
                [9.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::failure::AgentFailure
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::failure::AgentFailure>
    for crate::api::failure::AgentFailure
{
    fn into_into_dart(self) -> crate::api::failure::AgentFailure {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::session::AgentUiEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.operation_id.into_into_dart().into_dart(),
            self.call_id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.delta.into_into_dart().into_dart(),
            self.arguments_json.into_into_dart().into_dart(),
            self.output_preview.into_into_dart().into_dart(),
            self.ok.into_into_dart().into_dart(),
            self.stop_reason.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.input_tokens.into_into_dart().into_dart(),
            self.output_tokens.into_into_dart().into_dart(),
            self.resumed_ops.into_into_dart().into_dart(),
            self.recently_active.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::session::AgentUiEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::session::AgentUiEvent>
    for crate::api::session::AgentUiEvent
{
    fn into_into_dart(self) -> crate::api::session::AgentUiEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::catalog::AssembledPreview {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.tools.into_into_dart().into_dart(),
            self.warnings.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::catalog::AssembledPreview
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::catalog::AssembledPreview>
    for crate::api::catalog::AssembledPreview
{
    fn into_into_dart(self) -> crate::api::catalog::AssembledPreview {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::catalog::CapabilityEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.risk.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::catalog::CapabilityEntry
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::catalog::CapabilityEntry>
    for crate::api::catalog::CapabilityEntry
{
    fn into_into_dart(self) -> crate::api::catalog::CapabilityEntry {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::catalog::CatalogValidate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.on.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.budget.into_into_dart().into_dart(),
            self.dropped.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::catalog::CatalogValidate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::catalog::CatalogValidate>
    for crate::api::catalog::CatalogValidate
{
    fn into_into_dart(self) -> crate::api::catalog::CatalogValidate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::catalog::PreviewTool {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
            self.executor.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::catalog::PreviewTool
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::catalog::PreviewTool>
    for crate::api::catalog::PreviewTool
{
    fn into_into_dart(self) -> crate::api::catalog::PreviewTool {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::catalog::ReasoningSurface {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.note.into_into_dart().into_dart(),
            self.param.into_into_dart().into_dart(),
            self.default_on.into_into_dart().into_dart(),
            self.allowed.into_into_dart().into_dart(),
            self.default_value.into_into_dart().into_dart(),
            self.min.into_into_dart().into_dart(),
            self.max.into_into_dart().into_dart(),
            self.default_budget.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::catalog::ReasoningSurface
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::catalog::ReasoningSurface>
    for crate::api::catalog::ReasoningSurface
{
    fn into_into_dart(self) -> crate::api::catalog::ReasoningSurface {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::session::ResumeReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.resumed_ops.into_into_dart().into_dart(),
            self.statuses.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::session::ResumeReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::session::ResumeReport>
    for crate::api::session::ResumeReport
{
    fn into_into_dart(self) -> crate::api::session::ResumeReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::session::SessionSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.busy.into_into_dart().into_dart(),
            self.last_operation_id.into_into_dart().into_dart(),
            self.phase.into_into_dart().into_dart(),
            self.pending_call_ids.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::session::SessionSnapshot
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::session::SessionSnapshot>
    for crate::api::session::SessionSnapshot
{
    fn into_into_dart(self) -> crate::api::session::SessionSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::catalog::Skill {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
            self.version.into_into_dart().into_dart(),
            self.origin.into_into_dart().into_dart(),
            self.class_name.into_into_dart().into_dart(),
            self.dir.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::catalog::Skill {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::catalog::Skill>
    for crate::api::catalog::Skill
{
    fn into_into_dart(self) -> crate::api::catalog::Skill {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::catalog::Vendor {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
            self.group.into_into_dart().into_dart(),
            self.sort_rank.into_into_dart().into_dart(),
            self.default_base_url.into_into_dart().into_dart(),
            self.alt_base_urls.into_into_dart().into_dart(),
            self.dynamic_models.into_into_dart().into_dart(),
            self.custom_model.into_into_dart().into_dart(),
            self.default_model.into_into_dart().into_dart(),
            self.models.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::catalog::Vendor
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::catalog::Vendor>
    for crate::api::catalog::Vendor
{
    fn into_into_dart(self) -> crate::api::catalog::Vendor {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::failure::AgentFailure {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::failure::AgentFailure::MissingApiKey => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::failure::AgentFailure::UnknownProvider { name } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(name, serializer);
            }
            crate::api::failure::AgentFailure::InvalidUrl => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::failure::AgentFailure::Busy => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::failure::AgentFailure::UnknownSession => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::failure::AgentFailure::UnknownToolCall => {
                <i32>::sse_encode(5, serializer);
            }
            crate::api::failure::AgentFailure::RateLimited => {
                <i32>::sse_encode(6, serializer);
            }
            crate::api::failure::AgentFailure::ContextExceeded => {
                <i32>::sse_encode(7, serializer);
            }
            crate::api::failure::AgentFailure::Poisoned { recently_active } => {
                <i32>::sse_encode(8, serializer);
                <bool>::sse_encode(recently_active, serializer);
            }
            crate::api::failure::AgentFailure::Failed { message } => {
                <i32>::sse_encode(9, serializer);
                <String>::sse_encode(message, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::session::AgentUiEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.operation_id, serializer);
        <String>::sse_encode(self.call_id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.delta, serializer);
        <String>::sse_encode(self.arguments_json, serializer);
        <String>::sse_encode(self.output_preview, serializer);
        <bool>::sse_encode(self.ok, serializer);
        <String>::sse_encode(self.stop_reason, serializer);
        <String>::sse_encode(self.message, serializer);
        <u64>::sse_encode(self.input_tokens, serializer);
        <u64>::sse_encode(self.output_tokens, serializer);
        <Vec<String>>::sse_encode(self.resumed_ops, serializer);
        <bool>::sse_encode(self.recently_active, serializer);
    }
}

impl SseEncode for crate::api::catalog::AssembledPreview {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::catalog::PreviewTool>>::sse_encode(self.tools, serializer);
        <Vec<String>>::sse_encode(self.warnings, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::catalog::CapabilityEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.risk, serializer);
    }
}

impl SseEncode for crate::api::catalog::CatalogValidate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <bool>::sse_encode(self.on, serializer);
        <String>::sse_encode(self.value, serializer);
        <u32>::sse_encode(self.budget, serializer);
        <Vec<String>>::sse_encode(self.dropped, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::catalog::CapabilityEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::catalog::CapabilityEntry>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::catalog::PreviewTool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::catalog::PreviewTool>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::catalog::Skill> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::catalog::Skill>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::catalog::Vendor> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::catalog::Vendor>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::catalog::PreviewTool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.source, serializer);
        <String>::sse_encode(self.executor, serializer);
    }
}

impl SseEncode for crate::api::catalog::ReasoningSurface {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.note, serializer);
        <String>::sse_encode(self.param, serializer);
        <bool>::sse_encode(self.default_on, serializer);
        <Vec<String>>::sse_encode(self.allowed, serializer);
        <String>::sse_encode(self.default_value, serializer);
        <u32>::sse_encode(self.min, serializer);
        <u32>::sse_encode(self.max, serializer);
        <u32>::sse_encode(self.default_budget, serializer);
    }
}

impl SseEncode for crate::api::session::ResumeReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.resumed_ops, serializer);
        <Vec<String>>::sse_encode(self.statuses, serializer);
    }
}

impl SseEncode for crate::api::session::SessionSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.busy, serializer);
        <String>::sse_encode(self.last_operation_id, serializer);
        <String>::sse_encode(self.phase, serializer);
        <Vec<String>>::sse_encode(self.pending_call_ids, serializer);
    }
}

impl SseEncode for crate::api::catalog::Skill {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.description, serializer);
        <String>::sse_encode(self.version, serializer);
        <String>::sse_encode(self.origin, serializer);
        <String>::sse_encode(self.class_name, serializer);
        <String>::sse_encode(self.dir, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::catalog::Vendor {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.display_name, serializer);
        <String>::sse_encode(self.group, serializer);
        <u32>::sse_encode(self.sort_rank, serializer);
        <String>::sse_encode(self.default_base_url, serializer);
        <Vec<String>>::sse_encode(self.alt_base_urls, serializer);
        <bool>::sse_encode(self.dynamic_models, serializer);
        <bool>::sse_encode(self.custom_model, serializer);
        <String>::sse_encode(self.default_model, serializer);
        <Vec<String>>::sse_encode(self.models, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
