// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'failure.dart';
import 'handles.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `ack_from_receipt`, `empty_ack`, `supervisor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KimUiHandle>>
abstract class KimUiHandle implements RustOpaqueInterface {
  Future<AgentCatalogHandle> agentCatalog();

  Future<AgentFlags> agentFlags();

  Future<void> attachStore({required String dbPath});

  Future<Person> botCreate({
    required String clientProfileId,
    required String nickname,
    required String avatar,
    required String bio,
    required String model,
    required String thinkingEffort,
    required int contextTokens,
    required String visibility,
  });

  Future<String> botDelete({required String dest});

  Future<List<KimBotPendingItem>> botPending({
    required String dest,
    required int limit,
  });

  Future<KimTalkResult> botReply({
    required String dest,
    required String body,
    required PlatformInt64 inReplyTo,
    required String clientId,
  });

  Future<void> botTyping({
    required String dest,
    required int kind,
    required bool active,
  });

  Future<Person> botUpdate({
    required String dest,
    required String nickname,
    required String avatar,
    required String bio,
    required String model,
    required String thinkingEffort,
    required int contextTokens,
    required String visibility,
  });

  /// Seeds the desktop secret vault once. Not part of a turn payload.
  Future<void> cacheAgentSecret({
    required String keyRef,
    required String secret,
  });

  Future<void> cancelSend({required String clientId});

  Future<CommandAck> command({required UiCommand cmd});

  Future<ContactsHandle> contacts();

  Future<ConversationHandle> conversation({required String dest});

  /// Always callable. Does not open SQLite.
  static KimUiHandle create() =>
      RustLib.instance.api.crateApiClientKimUiHandleCreate();

  Future<void> deleteAgentProfile({required String profileId});

  Future<void> deleteProviderAccount({required String id});

  Future<void> deleteThread({required String dest});

  Future<KimCommandReceipt> enqueueMessage({
    required String dest,
    required int kind,
    required KimOutgoingContent content,
    required String clientId,
    required String localPath,
    required String mime,
    required int width,
    required int height,
    required PlatformInt64 byteSize,
  });

  Future<void> friendAccept({required String dest});

  Future<List<Person>> friendIncoming();

  Future<List<Person>> friendList();

  Future<void> friendReject({required String dest});

  Future<void> friendRemove({required String dest});

  Future<void> friendRequest({required String dest});

  Future<DeviceOverlay?> getDeviceOverlay({required String profileId});

  Future<void> importAgentProfiles({required List<AgentProfile> rows});

  Future<Settings> importDeviceSettings({
    required String wsUrl,
    required String httpOrigin,
    required String env,
    required String locale,
  });

  Future<InboxHandle> inbox();

  Future<List<AgentProfile>> listAgentProfiles();

  Future<List<ProviderAccount>> listProviderAccounts();

  Future<void> loadOlder({required String dest});

  Future<void> markConversationRead({required String dest, required int kind});

  Future<void> markRead({
    required String dest,
    required int kind,
    required PlatformInt64 messageId,
  });

  Future<void> markThreadRead({
    required String dest,
    required int kind,
    required PlatformInt64 messageId,
  });

  Future<MediaHandle> media();

  Future<LocalMedia> mediaFetch({required String url});

  Future<LocalMedia> mediaUpload({
    required String path,
    required String mime,
    required int width,
    required int height,
    required PlatformInt64 byteSize,
  });

  Metrics metricsSnapshot();

  Future<void> notifyForeground();

  Future<void> notifyRadioUp();

  Future<Profile> profile({required String dest});

  Future<void> refreshContacts();

  Future<void> respondAgentPermission({
    required String callId,
    required bool allow,
  });

  Future<KimCommandReceipt> retrySend({required String clientId});

  Future<List<RoomMember>> roomEnter({
    required String dest,
    required int kind,
  });

  Future<String> roomLeave({required String dest, required int kind});

  Future<List<MessageView>> searchMessages({
    required String query,
    String? dest,
  });

  Future<List<Person>> searchUsers({required String query});

  Future<void> sendTyping({
    required String dest,
    required int kind,
    required bool active,
  });

  Future<void> setAgentFlags({required AgentFlags flags});

  Future<void> setConversationVisibility({
    required BigInt generation,
    required bool foreground,
    required String dest,
    required int kind,
  });

  Future<Settings> settingsGet();

  Future<Settings> settingsPatch({
    String? wsUrl,
    String? httpOrigin,
    String? env,
  });

  Future<void> startSession({
    required String url,
    required String token,
    required String userAgent,
    required String account,
  });

  Future<void> stop();

  bool storeAttached();

  Future<void> submitAgentRun({required AgentRunResult result});

  Future<void> syncAgentSpecs();

  Future<Profile> updateProfile({
    required String nickname,
    required String avatar,
    required String bio,
  });

  Future<void> upsertAgentProfile({required AgentProfile row});

  Future<void> upsertDeviceOverlay({required DeviceOverlay row});

  Future<void> upsertProviderAccount({required ProviderAccount row});

  /// Desktop permission cards. Phone returns an idle stream.
  Stream<AgentPermissionEvent> watchAgentPermission();

  Stream<AgentRunRequest> watchAgentRun();

  /// Desktop pet presence (`running` / `done` / `failed`). Phone is idle.
  Stream<AgentUiStatus> watchAgentUi();

  Stream<ContactsSnapshot> watchContacts();

  /// Discrete Kickout/token/friend/agent events. Inbox/link live on snapshot.
  Stream<SessionUpdate> watchSession();

  Stream<SessionSnapshot> watchSessionSnapshot();

  Stream<TimelineUpdate> watchTimeline({
    required String dest,
    required int limit,
  });

  Stream<TokenPersist> watchTokenPersist();
}

class KimBotPendingItem {
  final PlatformInt64 messageId;
  final String body;
  final PlatformInt64 sendTime;

  const KimBotPendingItem({
    required this.messageId,
    required this.body,
    required this.sendTime,
  });

  @override
  int get hashCode => messageId.hashCode ^ body.hashCode ^ sendTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KimBotPendingItem &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          body == other.body &&
          sendTime == other.sendTime;
}

class KimCommandReceipt {
  final String requestId;
  final String clientId;
  final String dest;
  final PlatformInt64 acceptedAt;
  final SendStatus sendStatus;

  const KimCommandReceipt({
    required this.requestId,
    required this.clientId,
    required this.dest,
    required this.acceptedAt,
    required this.sendStatus,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      clientId.hashCode ^
      dest.hashCode ^
      acceptedAt.hashCode ^
      sendStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KimCommandReceipt &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          clientId == other.clientId &&
          dest == other.dest &&
          acceptedAt == other.acceptedAt &&
          sendStatus == other.sendStatus;
}

/// Wire content. `kind`: 1 text, 2 image, 3 voice, 4 video. `body` is text or URL.
class KimOutgoingContent {
  final int kind;
  final String body;
  final String extra;

  const KimOutgoingContent({
    required this.kind,
    required this.body,
    required this.extra,
  });

  @override
  int get hashCode => kind.hashCode ^ body.hashCode ^ extra.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KimOutgoingContent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          body == other.body &&
          extra == other.extra;
}

class KimTalkResult {
  final PlatformInt64 messageId;
  final PlatformInt64 sendTime;

  const KimTalkResult({required this.messageId, required this.sendTime});

  @override
  int get hashCode => messageId.hashCode ^ sendTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KimTalkResult &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          sendTime == other.sendTime;
}
