// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `supervisor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KimSdkHandle>>
abstract class KimSdkHandle implements RustOpaqueInterface {
  Future<void> attachStore({required String dbPath});

  Future<PersonDto> botCreate({
    required String clientProfileId,
    required String nickname,
    required String avatar,
    required String bio,
    required String model,
    required String thinkingEffort,
    required int contextTokens,
    required String visibility,
  });

  Future<String> botDelete({required String dest});

  Future<List<KimBotPendingItem>> botPending({
    required String dest,
    required int limit,
  });

  Future<KimTalkResult> botReply({
    required String dest,
    required String body,
    required PlatformInt64 inReplyTo,
    required String clientId,
  });

  Future<void> botTyping({
    required String dest,
    required int kind,
    required bool active,
  });

  Future<PersonDto> botUpdate({
    required String dest,
    required String nickname,
    required String avatar,
    required String bio,
    required String model,
    required String thinkingEffort,
    required int contextTokens,
    required String visibility,
  });

  Future<void> cancelSend({required String clientId});

  /// Always callable. Does not open SQLite.
  static KimSdkHandle create() =>
      RustLib.instance.api.crateApiClientKimSdkHandleCreate();

  Future<void> deleteAgentProfile({required String profileId});

  Future<void> deleteThread({required String dest});

  Future<KimCommandReceipt> enqueueMessage({
    required String dest,
    required int kind,
    required KimOutgoingContent content,
    required String clientId,
    required String localPath,
    required String mime,
    required int width,
    required int height,
    required PlatformInt64 byteSize,
  });

  Future<String> friendAccept({required String dest});

  Future<List<PersonDto>> friendIncoming();

  Future<List<PersonDto>> friendList();

  Future<String> friendReject({required String dest});

  Future<String> friendRemove({required String dest});

  Future<String> friendRequest({required String dest});

  Future<List<KimHistoryItem>> history({
    required String dest,
    required int kind,
    required PlatformInt64 beforeId,
    required int limit,
  });

  Future<void> importAgentProfiles({required List<AgentProfileDto> rows});

  Future<SettingsDto> importDeviceSettings({
    required String wsUrl,
    required String httpOrigin,
    required String env,
    required String locale,
  });

  Future<List<KimInboxItem>> inbox({required int limit});

  String linkState();

  Future<List<AgentProfileDto>> listAgentProfiles();

  Future<MessagePageDto> loadOlder({
    required String dest,
    required PlatformInt64 beforeAt,
    required String beforeKey,
    required PlatformInt64 beforeId,
    required int limit,
  });

  Future<void> markRead({
    required String dest,
    required int kind,
    required PlatformInt64 messageId,
  });

  Future<void> markThreadRead({
    required String dest,
    required int kind,
    required PlatformInt64 messageId,
  });

  Future<void> notifyForeground();

  Future<void> notifyRadioUp();

  Future<ProfileDto> profile({required String dest});

  Future<List<PersonDto>> refreshContacts();

  Future<KimCommandReceipt> retrySend({required String clientId});

  Future<List<RoomMemberDto>> roomEnter({
    required String dest,
    required int kind,
  });

  Future<String> roomLeave({required String dest, required int kind});

  Future<List<PersonDto>> searchUsers({required String query});

  Future<KimTalkResult> sendMessage({
    required String dest,
    required int kind,
    required KimOutgoingContent content,
    required String clientId,
  });

  Future<void> sendTyping({
    required String dest,
    required int kind,
    required bool active,
  });

  Future<SettingsDto> settingsGet();

  Future<SettingsDto> settingsPatch({
    String? wsUrl,
    String? httpOrigin,
    String? env,
  });

  Future<void> startSession({
    required String url,
    required String token,
    required String userAgent,
    required String account,
  });

  Future<void> stop();

  bool storeAttached();

  Future<void> submitAgentRun({required AgentRunResultDto result});

  Future<ProfileDto> updateProfile({
    required String nickname,
    required String avatar,
    required String bio,
  });

  Future<void> upsertAgentProfile({required AgentProfileDto row});

  Stream<AgentRunRequestDto> watchAgentRun();

  /// Typed mpsc for Kickout/token/friend. Not the Dart inbox — fat
  /// [`session_events`] remains the inbox until watch carries Snapshot/Delta.
  Stream<SessionUpdateDto> watchSession();

  Stream<SessionSnapshotDto> watchSessionSnapshot();

  Stream<TimelineUpdateDto> watchTimeline({
    required String dest,
    required int limit,
  });

  Stream<TokenPersistDto> watchTokenPersist();
}

class KimBotPendingItem {
  final PlatformInt64 messageId;
  final String body;
  final PlatformInt64 sendTime;

  const KimBotPendingItem({
    required this.messageId,
    required this.body,
    required this.sendTime,
  });

  @override
  int get hashCode => messageId.hashCode ^ body.hashCode ^ sendTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KimBotPendingItem &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          body == other.body &&
          sendTime == other.sendTime;
}

class KimCommandReceipt {
  final String requestId;
  final String clientId;
  final String dest;
  final PlatformInt64 acceptedAt;
  final SendStatusDto sendStatus;

  const KimCommandReceipt({
    required this.requestId,
    required this.clientId,
    required this.dest,
    required this.acceptedAt,
    required this.sendStatus,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      clientId.hashCode ^
      dest.hashCode ^
      acceptedAt.hashCode ^
      sendStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KimCommandReceipt &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          clientId == other.clientId &&
          dest == other.dest &&
          acceptedAt == other.acceptedAt &&
          sendStatus == other.sendStatus;
}

class KimHistoryItem {
  final PlatformInt64 messageId;
  final int msgType;
  final String body;
  final String extra;
  final String sender;
  final PlatformInt64 sendTime;
  final int direction;

  const KimHistoryItem({
    required this.messageId,
    required this.msgType,
    required this.body,
    required this.extra,
    required this.sender,
    required this.sendTime,
    required this.direction,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      msgType.hashCode ^
      body.hashCode ^
      extra.hashCode ^
      sender.hashCode ^
      sendTime.hashCode ^
      direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KimHistoryItem &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          msgType == other.msgType &&
          body == other.body &&
          extra == other.extra &&
          sender == other.sender &&
          sendTime == other.sendTime &&
          direction == other.direction;
}

class KimInboxItem {
  final String dest;
  final int kind;
  final String title;
  final String avatar;
  final String lastBody;
  final String lastSender;
  final PlatformInt64 lastMessageId;
  final PlatformInt64 lastSendTime;
  final int unread;

  const KimInboxItem({
    required this.dest,
    required this.kind,
    required this.title,
    required this.avatar,
    required this.lastBody,
    required this.lastSender,
    required this.lastMessageId,
    required this.lastSendTime,
    required this.unread,
  });

  @override
  int get hashCode =>
      dest.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      avatar.hashCode ^
      lastBody.hashCode ^
      lastSender.hashCode ^
      lastMessageId.hashCode ^
      lastSendTime.hashCode ^
      unread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KimInboxItem &&
          runtimeType == other.runtimeType &&
          dest == other.dest &&
          kind == other.kind &&
          title == other.title &&
          avatar == other.avatar &&
          lastBody == other.lastBody &&
          lastSender == other.lastSender &&
          lastMessageId == other.lastMessageId &&
          lastSendTime == other.lastSendTime &&
          unread == other.unread;
}

/// Wire content. `kind`: 1 text, 2 image, 3 voice, 4 video. `body` is text or URL.
class KimOutgoingContent {
  final int kind;
  final String body;
  final String extra;

  const KimOutgoingContent({
    required this.kind,
    required this.body,
    required this.extra,
  });

  @override
  int get hashCode => kind.hashCode ^ body.hashCode ^ extra.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KimOutgoingContent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          body == other.body &&
          extra == other.extra;
}

class KimTalkResult {
  final PlatformInt64 messageId;
  final PlatformInt64 sendTime;

  const KimTalkResult({required this.messageId, required this.sendTime});

  @override
  int get hashCode => messageId.hashCode ^ sendTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KimTalkResult &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          sendTime == other.sendTime;
}
