// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_profile`, `from_str`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MessagePageDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class AgentCardDto {
  final int v;
  final String cardType;
  final String callId;
  final String name;
  final String state;
  final String preview;
  final bool ok;

  const AgentCardDto({
    required this.v,
    required this.cardType,
    required this.callId,
    required this.name,
    required this.state,
    required this.preview,
    required this.ok,
  });

  @override
  int get hashCode =>
      v.hashCode ^
      cardType.hashCode ^
      callId.hashCode ^
      name.hashCode ^
      state.hashCode ^
      preview.hashCode ^
      ok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentCardDto &&
          runtimeType == other.runtimeType &&
          v == other.v &&
          cardType == other.cardType &&
          callId == other.callId &&
          name == other.name &&
          state == other.state &&
          preview == other.preview &&
          ok == other.ok;
}

class AgentProfileDto {
  final String profileId;
  final String nickname;
  final String serverAccount;
  final String bodyJson;
  final Uint8List bodyBlob;
  final String placement;
  final PlatformInt64 updatedAt;

  const AgentProfileDto({
    required this.profileId,
    required this.nickname,
    required this.serverAccount,
    required this.bodyJson,
    required this.bodyBlob,
    required this.placement,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      nickname.hashCode ^
      serverAccount.hashCode ^
      bodyJson.hashCode ^
      bodyBlob.hashCode ^
      placement.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentProfileDto &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          nickname == other.nickname &&
          serverAccount == other.serverAccount &&
          bodyJson == other.bodyJson &&
          bodyBlob == other.bodyBlob &&
          placement == other.placement &&
          updatedAt == other.updatedAt;
}

class AgentRunRequestDto {
  final String dest;
  final String profileId;
  final String text;
  final PlatformInt64 inReplyTo;
  final BigInt epoch;

  const AgentRunRequestDto({
    required this.dest,
    required this.profileId,
    required this.text,
    required this.inReplyTo,
    required this.epoch,
  });

  @override
  int get hashCode =>
      dest.hashCode ^
      profileId.hashCode ^
      text.hashCode ^
      inReplyTo.hashCode ^
      epoch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentRunRequestDto &&
          runtimeType == other.runtimeType &&
          dest == other.dest &&
          profileId == other.profileId &&
          text == other.text &&
          inReplyTo == other.inReplyTo &&
          epoch == other.epoch;
}

class AgentRunResultDto {
  final String dest;
  final String profileId;
  final BigInt epoch;
  final String output;
  final String? error;
  final String stopReason;
  final bool replied;
  final bool visible;
  final bool recentlyActive;

  const AgentRunResultDto({
    required this.dest,
    required this.profileId,
    required this.epoch,
    required this.output,
    this.error,
    required this.stopReason,
    required this.replied,
    required this.visible,
    required this.recentlyActive,
  });

  @override
  int get hashCode =>
      dest.hashCode ^
      profileId.hashCode ^
      epoch.hashCode ^
      output.hashCode ^
      error.hashCode ^
      stopReason.hashCode ^
      replied.hashCode ^
      visible.hashCode ^
      recentlyActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentRunResultDto &&
          runtimeType == other.runtimeType &&
          dest == other.dest &&
          profileId == other.profileId &&
          epoch == other.epoch &&
          output == other.output &&
          error == other.error &&
          stopReason == other.stopReason &&
          replied == other.replied &&
          visible == other.visible &&
          recentlyActive == other.recentlyActive;
}

enum AgentTurnStateDto {
  queued,
  running,
  waitingPermission,
  done,
  error,
  empty,
}

class BotDto {
  final String dest;
  final String nickname;
  final String avatar;
  final String bio;
  final String model;
  final String thinkingEffort;
  final int contextTokens;
  final String visibility;

  const BotDto({
    required this.dest,
    required this.nickname,
    required this.avatar,
    required this.bio,
    required this.model,
    required this.thinkingEffort,
    required this.contextTokens,
    required this.visibility,
  });

  @override
  int get hashCode =>
      dest.hashCode ^
      nickname.hashCode ^
      avatar.hashCode ^
      bio.hashCode ^
      model.hashCode ^
      thinkingEffort.hashCode ^
      contextTokens.hashCode ^
      visibility.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BotDto &&
          runtimeType == other.runtimeType &&
          dest == other.dest &&
          nickname == other.nickname &&
          avatar == other.avatar &&
          bio == other.bio &&
          model == other.model &&
          thinkingEffort == other.thinkingEffort &&
          contextTokens == other.contextTokens &&
          visibility == other.visibility;
}

class CommandAckDto {
  final String requestId;
  final String clientId;
  final String dest;
  final PlatformInt64 acceptedAt;
  final SendStatusDto sendStatus;

  const CommandAckDto({
    required this.requestId,
    required this.clientId,
    required this.dest,
    required this.acceptedAt,
    required this.sendStatus,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      clientId.hashCode ^
      dest.hashCode ^
      acceptedAt.hashCode ^
      sendStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandAckDto &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          clientId == other.clientId &&
          dest == other.dest &&
          acceptedAt == other.acceptedAt &&
          sendStatus == other.sendStatus;
}

class ContactsSnapshotDto {
  final BigInt version;
  final List<PersonDto> contacts;
  final String? syncError;

  const ContactsSnapshotDto({
    required this.version,
    required this.contacts,
    this.syncError,
  });

  @override
  int get hashCode => version.hashCode ^ contacts.hashCode ^ syncError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactsSnapshotDto &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          contacts == other.contacts &&
          syncError == other.syncError;
}

class DeviceOverlayDto {
  final String profileId;
  final String workspacePath;
  final String workspaceBookmark;
  final String userAgentsSkills;

  const DeviceOverlayDto({
    required this.profileId,
    required this.workspacePath,
    required this.workspaceBookmark,
    required this.userAgentsSkills,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      workspacePath.hashCode ^
      workspaceBookmark.hashCode ^
      userAgentsSkills.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceOverlayDto &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          workspacePath == other.workspacePath &&
          workspaceBookmark == other.workspaceBookmark &&
          userAgentsSkills == other.userAgentsSkills;
}

@freezed
sealed class LinkStateDto with _$LinkStateDto {
  const LinkStateDto._();

  const factory LinkStateDto.connecting() = LinkStateDto_Connecting;
  const factory LinkStateDto.online() = LinkStateDto_Online;
  const factory LinkStateDto.reconnecting({required int attempt}) =
      LinkStateDto_Reconnecting;
  const factory LinkStateDto.offline() = LinkStateDto_Offline;
}

class LocalMediaDto {
  final String localPath;
  final PlatformInt64 byteSize;
  final int width;
  final int height;

  const LocalMediaDto({
    required this.localPath,
    required this.byteSize,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      localPath.hashCode ^ byteSize.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalMediaDto &&
          runtimeType == other.runtimeType &&
          localPath == other.localPath &&
          byteSize == other.byteSize &&
          width == other.width &&
          height == other.height;
}

class MessageViewDto {
  final String key;
  final String dest;
  final String sender;
  final String body;
  final String? localPath;
  final PlatformInt64 at;
  final bool sys;
  final int kind;
  final int width;
  final int height;
  final PlatformInt64 messageId;
  final String? batchId;
  final SendStatusDto sendStatus;

  const MessageViewDto({
    required this.key,
    required this.dest,
    required this.sender,
    required this.body,
    this.localPath,
    required this.at,
    required this.sys,
    required this.kind,
    required this.width,
    required this.height,
    required this.messageId,
    this.batchId,
    required this.sendStatus,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      dest.hashCode ^
      sender.hashCode ^
      body.hashCode ^
      localPath.hashCode ^
      at.hashCode ^
      sys.hashCode ^
      kind.hashCode ^
      width.hashCode ^
      height.hashCode ^
      messageId.hashCode ^
      batchId.hashCode ^
      sendStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageViewDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          dest == other.dest &&
          sender == other.sender &&
          body == other.body &&
          localPath == other.localPath &&
          at == other.at &&
          sys == other.sys &&
          kind == other.kind &&
          width == other.width &&
          height == other.height &&
          messageId == other.messageId &&
          batchId == other.batchId &&
          sendStatus == other.sendStatus;
}

class MetricsDto {
  final BigInt enqueueTotal;
  final BigInt persistTalkTotal;
  final BigInt epochDropTotal;
  final BigInt storeWipeTotal;

  const MetricsDto({
    required this.enqueueTotal,
    required this.persistTalkTotal,
    required this.epochDropTotal,
    required this.storeWipeTotal,
  });

  @override
  int get hashCode =>
      enqueueTotal.hashCode ^
      persistTalkTotal.hashCode ^
      epochDropTotal.hashCode ^
      storeWipeTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetricsDto &&
          runtimeType == other.runtimeType &&
          enqueueTotal == other.enqueueTotal &&
          persistTalkTotal == other.persistTalkTotal &&
          epochDropTotal == other.epochDropTotal &&
          storeWipeTotal == other.storeWipeTotal;
}

class PersonDto {
  final String account;
  final String nickname;
  final String avatar;
  final String bio;
  final String relation;
  final int kind;

  const PersonDto({
    required this.account,
    required this.nickname,
    required this.avatar,
    required this.bio,
    required this.relation,
    required this.kind,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      nickname.hashCode ^
      avatar.hashCode ^
      bio.hashCode ^
      relation.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonDto &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          nickname == other.nickname &&
          avatar == other.avatar &&
          bio == other.bio &&
          relation == other.relation &&
          kind == other.kind;
}

class ProfileDto {
  final String account;
  final String nickname;
  final String avatar;
  final String bio;
  final int kind;

  const ProfileDto({
    required this.account,
    required this.nickname,
    required this.avatar,
    required this.bio,
    required this.kind,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      nickname.hashCode ^
      avatar.hashCode ^
      bio.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileDto &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          nickname == other.nickname &&
          avatar == other.avatar &&
          bio == other.bio &&
          kind == other.kind;
}

class ProviderAccountDto {
  final String id;
  final String vendorId;
  final String baseUrl;
  final String keyRef;
  final String displayName;
  final String modelsJson;
  final PlatformInt64 updatedAt;
  final PlatformInt64 deletedAt;

  const ProviderAccountDto({
    required this.id,
    required this.vendorId,
    required this.baseUrl,
    required this.keyRef,
    required this.displayName,
    required this.modelsJson,
    required this.updatedAt,
    required this.deletedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      vendorId.hashCode ^
      baseUrl.hashCode ^
      keyRef.hashCode ^
      displayName.hashCode ^
      modelsJson.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderAccountDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          vendorId == other.vendorId &&
          baseUrl == other.baseUrl &&
          keyRef == other.keyRef &&
          displayName == other.displayName &&
          modelsJson == other.modelsJson &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt;
}

class RoomMemberDto {
  final String account;
  final int status;
  final PlatformInt64 lastSeen;

  const RoomMemberDto({
    required this.account,
    required this.status,
    required this.lastSeen,
  });

  @override
  int get hashCode => account.hashCode ^ status.hashCode ^ lastSeen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomMemberDto &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          status == other.status &&
          lastSeen == other.lastSeen;
}

class SdkErrorDto implements FrbException {
  final String kind;
  final String message;

  const SdkErrorDto({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SdkErrorDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum SendStatusDto { pending, uploading, sending, sent, failed, cancelled }

class SessionSnapshotDto {
  final LinkStateDto link;
  final String? lastError;
  final List<ThreadViewDto> threads;
  final int unreadTotal;

  const SessionSnapshotDto({
    required this.link,
    this.lastError,
    required this.threads,
    required this.unreadTotal,
  });

  @override
  int get hashCode =>
      link.hashCode ^
      lastError.hashCode ^
      threads.hashCode ^
      unreadTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSnapshotDto &&
          runtimeType == other.runtimeType &&
          link == other.link &&
          lastError == other.lastError &&
          threads == other.threads &&
          unreadTotal == other.unreadTotal;
}

@freezed
sealed class SessionUpdateDto with _$SessionUpdateDto {
  const SessionUpdateDto._();

  const factory SessionUpdateDto.link({
    required LinkStateDto state,
    String? lastError,
  }) = SessionUpdateDto_Link;
  const factory SessionUpdateDto.inbox({required List<ThreadViewDto> threads}) =
      SessionUpdateDto_Inbox;
  const factory SessionUpdateDto.threadUpsert({required ThreadViewDto thread}) =
      SessionUpdateDto_ThreadUpsert;
  const factory SessionUpdateDto.syncProgress({
    required BigInt pulled,
    required bool catchingUp,
  }) = SessionUpdateDto_SyncProgress;
  const factory SessionUpdateDto.kickout({required String channelId}) =
      SessionUpdateDto_Kickout;
  const factory SessionUpdateDto.authExpired({required String reason}) =
      SessionUpdateDto_AuthExpired;
  const factory SessionUpdateDto.tokenRenew({
    required String token,
    required PlatformInt64 exp,
  }) = SessionUpdateDto_TokenRenew;
  const factory SessionUpdateDto.friendRequest({
    required String from,
    required String nickname,
  }) = SessionUpdateDto_FriendRequest;
  const factory SessionUpdateDto.friendAccepted({
    required String from,
    required String nickname,
  }) = SessionUpdateDto_FriendAccepted;
  const factory SessionUpdateDto.profileUpdated({
    required String account,
    required String nickname,
    required String avatar,
  }) = SessionUpdateDto_ProfileUpdated;
  const factory SessionUpdateDto.presence({
    required String account,
    required int status,
    required PlatformInt64 lastSeen,
  }) = SessionUpdateDto_Presence;
  const factory SessionUpdateDto.typing({
    required String typer,
    required String dest,
    required int kind,
    required bool active,
  }) = SessionUpdateDto_Typing;
  const factory SessionUpdateDto.receiptRead({
    required String reader,
    required String dest,
    required int kind,
    required PlatformInt64 messageId,
  }) = SessionUpdateDto_ReceiptRead;
  const factory SessionUpdateDto.groupCreate({
    required String groupId,
    required List<String> members,
  }) = SessionUpdateDto_GroupCreate;
  const factory SessionUpdateDto.contactsChanged({
    required List<PersonDto> contacts,
  }) = SessionUpdateDto_ContactsChanged;
  const factory SessionUpdateDto.agentTurn({
    required String dest,
    required AgentTurnStateDto state,
    required String text,
  }) = SessionUpdateDto_AgentTurn;
  const factory SessionUpdateDto.agentCard({
    required String dest,
    required AgentCardDto card,
  }) = SessionUpdateDto_AgentCard;
  const factory SessionUpdateDto.rustPanic({required String message}) =
      SessionUpdateDto_RustPanic;
}

class SettingsDto {
  final String wsUrl;
  final String httpOrigin;
  final String env;
  final String locale;
  final String account;

  const SettingsDto({
    required this.wsUrl,
    required this.httpOrigin,
    required this.env,
    required this.locale,
    required this.account,
  });

  @override
  int get hashCode =>
      wsUrl.hashCode ^
      httpOrigin.hashCode ^
      env.hashCode ^
      locale.hashCode ^
      account.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsDto &&
          runtimeType == other.runtimeType &&
          wsUrl == other.wsUrl &&
          httpOrigin == other.httpOrigin &&
          env == other.env &&
          locale == other.locale &&
          account == other.account;
}

class ThreadViewDto {
  final String id;
  final int kind;
  final String title;
  final String avatar;
  final String lastBody;
  final PlatformInt64 lastAt;
  final int unread;

  const ThreadViewDto({
    required this.id,
    required this.kind,
    required this.title,
    required this.avatar,
    required this.lastBody,
    required this.lastAt,
    required this.unread,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      avatar.hashCode ^
      lastBody.hashCode ^
      lastAt.hashCode ^
      unread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadViewDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          title == other.title &&
          avatar == other.avatar &&
          lastBody == other.lastBody &&
          lastAt == other.lastAt &&
          unread == other.unread;
}

class TimelineDeltaDto {
  final String dest;
  final BigInt fromVersion;
  final BigInt toVersion;
  final List<MessageViewDto> upserts;
  final List<String> deletedKeys;
  final int? unread;
  final PlatformInt64? lastReadMessageId;

  const TimelineDeltaDto({
    required this.dest,
    required this.fromVersion,
    required this.toVersion,
    required this.upserts,
    required this.deletedKeys,
    this.unread,
    this.lastReadMessageId,
  });

  @override
  int get hashCode =>
      dest.hashCode ^
      fromVersion.hashCode ^
      toVersion.hashCode ^
      upserts.hashCode ^
      deletedKeys.hashCode ^
      unread.hashCode ^
      lastReadMessageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineDeltaDto &&
          runtimeType == other.runtimeType &&
          dest == other.dest &&
          fromVersion == other.fromVersion &&
          toVersion == other.toVersion &&
          upserts == other.upserts &&
          deletedKeys == other.deletedKeys &&
          unread == other.unread &&
          lastReadMessageId == other.lastReadMessageId;
}

class TimelineSnapshotDto {
  final String dest;
  final BigInt version;
  final List<MessageViewDto> messages;
  final List<MessageViewDto> pending;
  final int unread;
  final PlatformInt64 lastReadMessageId;
  final bool hasMore;
  final bool loadingOlder;
  final String? historyError;

  const TimelineSnapshotDto({
    required this.dest,
    required this.version,
    required this.messages,
    required this.pending,
    required this.unread,
    required this.lastReadMessageId,
    required this.hasMore,
    required this.loadingOlder,
    this.historyError,
  });

  @override
  int get hashCode =>
      dest.hashCode ^
      version.hashCode ^
      messages.hashCode ^
      pending.hashCode ^
      unread.hashCode ^
      lastReadMessageId.hashCode ^
      hasMore.hashCode ^
      loadingOlder.hashCode ^
      historyError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineSnapshotDto &&
          runtimeType == other.runtimeType &&
          dest == other.dest &&
          version == other.version &&
          messages == other.messages &&
          pending == other.pending &&
          unread == other.unread &&
          lastReadMessageId == other.lastReadMessageId &&
          hasMore == other.hasMore &&
          loadingOlder == other.loadingOlder &&
          historyError == other.historyError;
}

@freezed
sealed class TimelineUpdateDto with _$TimelineUpdateDto {
  const TimelineUpdateDto._();

  const factory TimelineUpdateDto.snapshot({
    required TimelineSnapshotDto snapshot,
  }) = TimelineUpdateDto_Snapshot;
  const factory TimelineUpdateDto.delta({required TimelineDeltaDto delta}) =
      TimelineUpdateDto_Delta;
  const factory TimelineUpdateDto.resync({
    required String dest,
    required String reason,
  }) = TimelineUpdateDto_Resync;
}

@freezed
sealed class TokenPersistDto with _$TokenPersistDto {
  const TokenPersistDto._();

  const factory TokenPersistDto.write({required String token}) =
      TokenPersistDto_Write;
  const factory TokenPersistDto.clear() = TokenPersistDto_Clear;
}

@freezed
sealed class UiCommandDto with _$UiCommandDto {
  const UiCommandDto._();

  const factory UiCommandDto.sendText({
    required String dest,
    required String text,
    required int kind,
  }) = UiCommandDto_SendText;
  const factory UiCommandDto.sendMedia({
    required String dest,
    required String path,
    required String mime,
    required int width,
    required int height,
    required PlatformInt64 byteSize,
    required int kind,
  }) = UiCommandDto_SendMedia;
  const factory UiCommandDto.retrySend({required String clientId}) =
      UiCommandDto_RetrySend;
  const factory UiCommandDto.cancelSend({required String clientId}) =
      UiCommandDto_CancelSend;
  const factory UiCommandDto.markThreadRead({
    required String dest,
    required int kind,
    required PlatformInt64 visibleMessageId,
  }) = UiCommandDto_MarkThreadRead;
  const factory UiCommandDto.deleteThread({required String dest}) =
      UiCommandDto_DeleteThread;
  const factory UiCommandDto.friendRequest({required String dest}) =
      UiCommandDto_FriendRequest;
  const factory UiCommandDto.friendAccept({required String dest}) =
      UiCommandDto_FriendAccept;
  const factory UiCommandDto.friendReject({required String dest}) =
      UiCommandDto_FriendReject;
  const factory UiCommandDto.friendRemove({required String dest}) =
      UiCommandDto_FriendRemove;
  const factory UiCommandDto.agentEnqueueTurn({
    required String dest,
    required String text,
    required PlatformInt64 inReplyTo,
  }) = UiCommandDto_AgentEnqueueTurn;
  const factory UiCommandDto.agentRespondPermission({
    required String dest,
    required String callId,
    required String permission,
  }) = UiCommandDto_AgentRespondPermission;
  const factory UiCommandDto.agentAbortTurn({required String dest}) =
      UiCommandDto_AgentAbortTurn;
  const factory UiCommandDto.agentRunResult({
    required String dest,
    required String profileId,
    required BigInt epoch,
    required String output,
    String? error,
  }) = UiCommandDto_AgentRunResult;
  const factory UiCommandDto.settingsPatch({
    String? wsUrl,
    String? httpOrigin,
    String? env,
  }) = UiCommandDto_SettingsPatch;
}
