// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SdkErrorDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`

class SessionUpdateDto {
  final String kind;
  final String channelId;
  final String reason;
  final String token;
  final PlatformInt64 exp;
  final String from;
  final String nickname;
  final BigInt pulled;
  final bool catchingUp;
  final String? lastError;
  final int inboxCount;

  const SessionUpdateDto({
    required this.kind,
    required this.channelId,
    required this.reason,
    required this.token,
    required this.exp,
    required this.from,
    required this.nickname,
    required this.pulled,
    required this.catchingUp,
    this.lastError,
    required this.inboxCount,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      channelId.hashCode ^
      reason.hashCode ^
      token.hashCode ^
      exp.hashCode ^
      from.hashCode ^
      nickname.hashCode ^
      pulled.hashCode ^
      catchingUp.hashCode ^
      lastError.hashCode ^
      inboxCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionUpdateDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          channelId == other.channelId &&
          reason == other.reason &&
          token == other.token &&
          exp == other.exp &&
          from == other.from &&
          nickname == other.nickname &&
          pulled == other.pulled &&
          catchingUp == other.catchingUp &&
          lastError == other.lastError &&
          inboxCount == other.inboxCount;
}

class TimelineUpdateDto {
  final String kind;
  final String dest;
  final BigInt version;
  final BigInt fromVersion;
  final BigInt toVersion;
  final int unread;
  final bool hasMore;
  final String reason;

  const TimelineUpdateDto({
    required this.kind,
    required this.dest,
    required this.version,
    required this.fromVersion,
    required this.toVersion,
    required this.unread,
    required this.hasMore,
    required this.reason,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      dest.hashCode ^
      version.hashCode ^
      fromVersion.hashCode ^
      toVersion.hashCode ^
      unread.hashCode ^
      hasMore.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineUpdateDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          dest == other.dest &&
          version == other.version &&
          fromVersion == other.fromVersion &&
          toVersion == other.toVersion &&
          unread == other.unread &&
          hasMore == other.hasMore &&
          reason == other.reason;
}
