// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_profile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class AgentCard {
  final String callId;
  final String name;
  final AgentCardType cardType;
  final AgentCardState state;
  final String preview;
  final bool ok;

  const AgentCard({
    required this.callId,
    required this.name,
    required this.cardType,
    required this.state,
    required this.preview,
    required this.ok,
  });

  @override
  int get hashCode =>
      callId.hashCode ^
      name.hashCode ^
      cardType.hashCode ^
      state.hashCode ^
      preview.hashCode ^
      ok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentCard &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          name == other.name &&
          cardType == other.cardType &&
          state == other.state &&
          preview == other.preview &&
          ok == other.ok;
}

enum AgentCardState { pending, ok, error }

enum AgentCardType { tool, actionRequired }

class AgentFlags {
  final bool multiProfile;
  final bool serverIdentity;

  const AgentFlags({required this.multiProfile, required this.serverIdentity});

  @override
  int get hashCode => multiProfile.hashCode ^ serverIdentity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentFlags &&
          runtimeType == other.runtimeType &&
          multiProfile == other.multiProfile &&
          serverIdentity == other.serverIdentity;
}

class AgentProfile {
  final String profileId;
  final String nickname;
  final String serverAccount;
  final String documentJson;
  final ProfilePlacement placement;
  final PlatformInt64 updatedAt;

  const AgentProfile({
    required this.profileId,
    required this.nickname,
    required this.serverAccount,
    required this.documentJson,
    required this.placement,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      nickname.hashCode ^
      serverAccount.hashCode ^
      documentJson.hashCode ^
      placement.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentProfile &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          nickname == other.nickname &&
          serverAccount == other.serverAccount &&
          documentJson == other.documentJson &&
          placement == other.placement &&
          updatedAt == other.updatedAt;
}

enum AgentTurnState { queued, running, waitingPermission, done, error, empty }

class ContactsSnapshot {
  final BigInt version;
  final List<Person> contacts;
  final String? syncError;

  const ContactsSnapshot({
    required this.version,
    required this.contacts,
    this.syncError,
  });

  @override
  int get hashCode => version.hashCode ^ contacts.hashCode ^ syncError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactsSnapshot &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          contacts == other.contacts &&
          syncError == other.syncError;
}

class DeviceOverlay {
  final String profileId;
  final String workspacePath;
  final String workspaceBookmark;
  final String userAgentsSkills;

  const DeviceOverlay({
    required this.profileId,
    required this.workspacePath,
    required this.workspaceBookmark,
    required this.userAgentsSkills,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      workspacePath.hashCode ^
      workspaceBookmark.hashCode ^
      userAgentsSkills.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceOverlay &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          workspacePath == other.workspacePath &&
          workspaceBookmark == other.workspaceBookmark &&
          userAgentsSkills == other.userAgentsSkills;
}

@freezed
sealed class LinkState with _$LinkState {
  const LinkState._();

  const factory LinkState.connecting() = LinkState_Connecting;
  const factory LinkState.online() = LinkState_Online;
  const factory LinkState.reconnecting({required int attempt}) =
      LinkState_Reconnecting;
  const factory LinkState.offline() = LinkState_Offline;
}

class LocalMedia {
  final String localPath;
  final PlatformInt64 byteSize;
  final int width;
  final int height;

  const LocalMedia({
    required this.localPath,
    required this.byteSize,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      localPath.hashCode ^ byteSize.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalMedia &&
          runtimeType == other.runtimeType &&
          localPath == other.localPath &&
          byteSize == other.byteSize &&
          width == other.width &&
          height == other.height;
}

enum MediaKind { text, image, video, voice, card }

class MessageView {
  final String key;
  final String dest;
  final String sender;
  final String body;
  final String? localPath;
  final PlatformInt64 at;
  final bool sys;
  final MediaKind kind;
  final AgentCard? card;
  final int width;
  final int height;
  final PlatformInt64 messageId;
  final String? batchId;
  final SendStatus sendStatus;

  const MessageView({
    required this.key,
    required this.dest,
    required this.sender,
    required this.body,
    this.localPath,
    required this.at,
    required this.sys,
    required this.kind,
    this.card,
    required this.width,
    required this.height,
    required this.messageId,
    this.batchId,
    required this.sendStatus,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      dest.hashCode ^
      sender.hashCode ^
      body.hashCode ^
      localPath.hashCode ^
      at.hashCode ^
      sys.hashCode ^
      kind.hashCode ^
      card.hashCode ^
      width.hashCode ^
      height.hashCode ^
      messageId.hashCode ^
      batchId.hashCode ^
      sendStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageView &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          dest == other.dest &&
          sender == other.sender &&
          body == other.body &&
          localPath == other.localPath &&
          at == other.at &&
          sys == other.sys &&
          kind == other.kind &&
          card == other.card &&
          width == other.width &&
          height == other.height &&
          messageId == other.messageId &&
          batchId == other.batchId &&
          sendStatus == other.sendStatus;
}

class Metrics {
  final BigInt enqueueTotal;
  final BigInt persistTalkTotal;
  final BigInt epochDropTotal;
  final BigInt storeWipeTotal;

  const Metrics({
    required this.enqueueTotal,
    required this.persistTalkTotal,
    required this.epochDropTotal,
    required this.storeWipeTotal,
  });

  @override
  int get hashCode =>
      enqueueTotal.hashCode ^
      persistTalkTotal.hashCode ^
      epochDropTotal.hashCode ^
      storeWipeTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Metrics &&
          runtimeType == other.runtimeType &&
          enqueueTotal == other.enqueueTotal &&
          persistTalkTotal == other.persistTalkTotal &&
          epochDropTotal == other.epochDropTotal &&
          storeWipeTotal == other.storeWipeTotal;
}

@freezed
sealed class OutgoingContent with _$OutgoingContent {
  const OutgoingContent._();

  const factory OutgoingContent.text({required String body}) =
      OutgoingContent_Text;
  const factory OutgoingContent.image({
    required String path,
    required String mime,
    required int width,
    required int height,
    required PlatformInt64 byteSize,
  }) = OutgoingContent_Image;
  const factory OutgoingContent.video({
    required String path,
    required PlatformInt64 byteSize,
  }) = OutgoingContent_Video;
  const factory OutgoingContent.voice({
    required String path,
    required PlatformInt64 byteSize,
  }) = OutgoingContent_Voice;
}

class Person {
  final String account;
  final String nickname;
  final String avatar;
  final String bio;
  final Relation relation;
  final ProfileKind kind;

  const Person({
    required this.account,
    required this.nickname,
    required this.avatar,
    required this.bio,
    required this.relation,
    required this.kind,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      nickname.hashCode ^
      avatar.hashCode ^
      bio.hashCode ^
      relation.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Person &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          nickname == other.nickname &&
          avatar == other.avatar &&
          bio == other.bio &&
          relation == other.relation &&
          kind == other.kind;
}

class Profile {
  final String account;
  final String nickname;
  final String avatar;
  final String bio;
  final ProfileKind kind;

  const Profile({
    required this.account,
    required this.nickname,
    required this.avatar,
    required this.bio,
    required this.kind,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      nickname.hashCode ^
      avatar.hashCode ^
      bio.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Profile &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          nickname == other.nickname &&
          avatar == other.avatar &&
          bio == other.bio &&
          kind == other.kind;
}

enum ProfileKind { user, bot }

enum ProfilePlacement { local, cloud }

class ProviderAccount {
  final String id;
  final String vendorId;
  final String baseUrl;
  final String keyRef;
  final String displayName;
  final List<String> models;
  final PlatformInt64 updatedAt;

  const ProviderAccount({
    required this.id,
    required this.vendorId,
    required this.baseUrl,
    required this.keyRef,
    required this.displayName,
    required this.models,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      vendorId.hashCode ^
      baseUrl.hashCode ^
      keyRef.hashCode ^
      displayName.hashCode ^
      models.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderAccount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          vendorId == other.vendorId &&
          baseUrl == other.baseUrl &&
          keyRef == other.keyRef &&
          displayName == other.displayName &&
          models == other.models &&
          updatedAt == other.updatedAt;
}

enum Relation { friend, incoming, outgoing }

class RoomMember {
  final String account;
  final int status;
  final PlatformInt64 lastSeen;

  const RoomMember({
    required this.account,
    required this.status,
    required this.lastSeen,
  });

  @override
  int get hashCode => account.hashCode ^ status.hashCode ^ lastSeen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomMember &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          status == other.status &&
          lastSeen == other.lastSeen;
}

enum SendStatus { pending, uploading, sending, sent, failed, cancelled }

class SessionSnapshot {
  final LinkState link;
  final String? lastError;
  final List<ThreadView> threads;
  final int unreadTotal;

  const SessionSnapshot({
    required this.link,
    this.lastError,
    required this.threads,
    required this.unreadTotal,
  });

  @override
  int get hashCode =>
      link.hashCode ^
      lastError.hashCode ^
      threads.hashCode ^
      unreadTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSnapshot &&
          runtimeType == other.runtimeType &&
          link == other.link &&
          lastError == other.lastError &&
          threads == other.threads &&
          unreadTotal == other.unreadTotal;
}

@freezed
sealed class SessionUpdate with _$SessionUpdate {
  const SessionUpdate._();

  const factory SessionUpdate.link({
    required LinkState state,
    String? lastError,
  }) = SessionUpdate_Link;
  const factory SessionUpdate.inbox({required List<ThreadView> threads}) =
      SessionUpdate_Inbox;
  const factory SessionUpdate.threadUpsert({required ThreadView thread}) =
      SessionUpdate_ThreadUpsert;
  const factory SessionUpdate.syncProgress({
    required BigInt pulled,
    required bool catchingUp,
  }) = SessionUpdate_SyncProgress;
  const factory SessionUpdate.kickout({required String channelId}) =
      SessionUpdate_Kickout;
  const factory SessionUpdate.authExpired({required String reason}) =
      SessionUpdate_AuthExpired;
  const factory SessionUpdate.friendRequest({
    required String from,
    required String nickname,
  }) = SessionUpdate_FriendRequest;
  const factory SessionUpdate.friendAccepted({
    required String from,
    required String nickname,
  }) = SessionUpdate_FriendAccepted;
  const factory SessionUpdate.profileUpdated({
    required String account,
    required String nickname,
    required String avatar,
  }) = SessionUpdate_ProfileUpdated;
  const factory SessionUpdate.presence({
    required String account,
    required int status,
    required PlatformInt64 lastSeen,
  }) = SessionUpdate_Presence;
  const factory SessionUpdate.typing({
    required String typer,
    required String dest,
    required ThreadKind kind,
    required bool active,
  }) = SessionUpdate_Typing;
  const factory SessionUpdate.receiptRead({
    required String reader,
    required String dest,
    required ThreadKind kind,
    required PlatformInt64 messageId,
  }) = SessionUpdate_ReceiptRead;
  const factory SessionUpdate.groupCreate({
    required String groupId,
    required List<String> members,
  }) = SessionUpdate_GroupCreate;
  const factory SessionUpdate.contactsChanged({
    required List<Person> contacts,
  }) = SessionUpdate_ContactsChanged;
  const factory SessionUpdate.agentTurn({
    required String dest,
    required AgentTurnState state,
    required String text,
  }) = SessionUpdate_AgentTurn;
  const factory SessionUpdate.agentCard({
    required String dest,
    required AgentCard card,
  }) = SessionUpdate_AgentCard;
  const factory SessionUpdate.rustPanic({required String message}) =
      SessionUpdate_RustPanic;
}

class Settings {
  final String wsUrl;
  final String httpOrigin;
  final String env;
  final String locale;
  final String account;

  const Settings({
    required this.wsUrl,
    required this.httpOrigin,
    required this.env,
    required this.locale,
    required this.account,
  });

  @override
  int get hashCode =>
      wsUrl.hashCode ^
      httpOrigin.hashCode ^
      env.hashCode ^
      locale.hashCode ^
      account.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          wsUrl == other.wsUrl &&
          httpOrigin == other.httpOrigin &&
          env == other.env &&
          locale == other.locale &&
          account == other.account;
}

enum SettingsPreset { local, prod }

enum ThreadKind { user, group }

@freezed
sealed class ThreadPreview with _$ThreadPreview {
  const ThreadPreview._();

  const factory ThreadPreview.text({required String snippet}) =
      ThreadPreview_Text;
  const factory ThreadPreview.media({required MediaKind kind}) =
      ThreadPreview_Media;
  const factory ThreadPreview.system({required String text}) =
      ThreadPreview_System;
}

class ThreadView {
  final String id;
  final ThreadKind kind;
  final String title;
  final String avatar;
  final String lastBody;
  final ThreadPreview preview;
  final PlatformInt64 lastAt;
  final int unread;

  const ThreadView({
    required this.id,
    required this.kind,
    required this.title,
    required this.avatar,
    required this.lastBody,
    required this.preview,
    required this.lastAt,
    required this.unread,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      avatar.hashCode ^
      lastBody.hashCode ^
      preview.hashCode ^
      lastAt.hashCode ^
      unread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          title == other.title &&
          avatar == other.avatar &&
          lastBody == other.lastBody &&
          preview == other.preview &&
          lastAt == other.lastAt &&
          unread == other.unread;
}

class TimelineDelta {
  final String dest;
  final BigInt fromVersion;
  final BigInt toVersion;
  final List<MessageView> upserts;
  final List<String> deletedKeys;
  final int? unread;
  final PlatformInt64? lastReadMessageId;

  const TimelineDelta({
    required this.dest,
    required this.fromVersion,
    required this.toVersion,
    required this.upserts,
    required this.deletedKeys,
    this.unread,
    this.lastReadMessageId,
  });

  @override
  int get hashCode =>
      dest.hashCode ^
      fromVersion.hashCode ^
      toVersion.hashCode ^
      upserts.hashCode ^
      deletedKeys.hashCode ^
      unread.hashCode ^
      lastReadMessageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineDelta &&
          runtimeType == other.runtimeType &&
          dest == other.dest &&
          fromVersion == other.fromVersion &&
          toVersion == other.toVersion &&
          upserts == other.upserts &&
          deletedKeys == other.deletedKeys &&
          unread == other.unread &&
          lastReadMessageId == other.lastReadMessageId;
}

class TimelineSnapshot {
  final String dest;
  final BigInt version;
  final List<MessageView> messages;
  final List<MessageView> pending;
  final int unread;
  final PlatformInt64 lastReadMessageId;
  final bool hasMore;
  final bool loadingOlder;
  final String? historyError;

  const TimelineSnapshot({
    required this.dest,
    required this.version,
    required this.messages,
    required this.pending,
    required this.unread,
    required this.lastReadMessageId,
    required this.hasMore,
    required this.loadingOlder,
    this.historyError,
  });

  @override
  int get hashCode =>
      dest.hashCode ^
      version.hashCode ^
      messages.hashCode ^
      pending.hashCode ^
      unread.hashCode ^
      lastReadMessageId.hashCode ^
      hasMore.hashCode ^
      loadingOlder.hashCode ^
      historyError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineSnapshot &&
          runtimeType == other.runtimeType &&
          dest == other.dest &&
          version == other.version &&
          messages == other.messages &&
          pending == other.pending &&
          unread == other.unread &&
          lastReadMessageId == other.lastReadMessageId &&
          hasMore == other.hasMore &&
          loadingOlder == other.loadingOlder &&
          historyError == other.historyError;
}

@freezed
sealed class TimelineUpdate with _$TimelineUpdate {
  const TimelineUpdate._();

  const factory TimelineUpdate.snapshot({required TimelineSnapshot snapshot}) =
      TimelineUpdate_Snapshot;
  const factory TimelineUpdate.delta({required TimelineDelta delta}) =
      TimelineUpdate_Delta;
  const factory TimelineUpdate.resync({
    required String dest,
    required String reason,
  }) = TimelineUpdate_Resync;
}
