use bytes::Bytes;
use kim_protocol::pkt::{KickoutNotify, LoginResp, Status};
use kim_router::{Context, SessionError};
use tracing::{error, info, warn};

pub async fn do_sys_login(ctx: Context) {
    do_sys_login_with_zone(ctx, "").await;
}

pub async fn do_sys_login_with_zone(ctx: Context, zone: &str) {
    let body = match ctx.read_body::<kim_protocol::pkt::Session>() {
        Ok(s) if !s.account.is_empty() => s,
        Ok(_) | Err(_) => {
            if let Err(err) = ctx
                .resp_bytes(Status::InvalidPacketBody, Bytes::new())
                .await
            {
                warn!(%err, "resp failed");
            }
            return;
        }
    };
    let mut body = body;
    if !zone.is_empty() {
        body.zone = zone.to_string();
    }
    info!(account = %body.account, channel = %body.channel_id, zone = %body.zone, "do login");
    match ctx.get_location(&body.account, "").await {
        Err(SessionError::NotFound) => {}
        Err(err) => {
            warn!(%err, "get_location failed");
            if let Err(e) = ctx.resp_bytes(Status::SystemException, Bytes::new()).await {
                warn!(%e, "resp failed");
            }
            return;
        }
        Ok(old) => {
            info!(
                old_channel = %old.channel_id,
                new_channel = %body.channel_id,
                "kickout"
            );
            let notify = KickoutNotify {
                channel_id: old.channel_id.clone(),
            };
            if let Err(err) = ctx.dispatch(&notify, std::slice::from_ref(&old)).await {
                warn!(%err, "dispatch kickout failed");
            }
        }
    }
    if let Err(err) = ctx.add(&body).await {
        error!(%err, "session add failed");
        if let Err(e) = ctx.resp_bytes(Status::SystemException, Bytes::new()).await {
            warn!(%e, "resp failed");
        }
        return;
    }
    let resp = LoginResp {
        channel_id: body.channel_id.clone(),
    };
    if let Err(err) = ctx.resp(Status::Success, Some(&resp)).await {
        warn!(%err, "resp failed");
    }
}

pub async fn do_sys_logout(ctx: Context) {
    let account = ctx.session().account.clone();
    let channel_id = ctx.session().channel_id.clone();
    info!(account = %account, channel = %channel_id, "do logout");
    match ctx.delete(&account, &channel_id).await {
        Ok(()) => {
            if let Err(err) = ctx.resp_bytes(Status::Success, Bytes::new()).await {
                warn!(%err, "resp failed");
            }
        }
        Err(err) => {
            warn!(%err, "delete failed");
            if let Err(e) = ctx.resp_bytes(Status::SystemException, Bytes::new()).await {
                warn!(%e, "resp failed");
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::sync::{Arc, Mutex};

    use async_trait::async_trait;
    use bytes::Bytes;
    use kim_protocol::pkt::{Flag, KickoutNotify, Session, Status};
    use kim_protocol::{LogicPkt, CMD_LOGIN_SIGN_IN, META_DEST_CHANNELS, META_DEST_SERVER};
    use kim_router::{Dispatcher, Router, RouterError, SessionStorage};
    use kim_session::MemorySessionStore;

    use super::do_sys_login;

    #[derive(Default)]
    struct RecordingDispatcher {
        pushes: Mutex<Vec<LogicPkt>>,
    }

    impl RecordingDispatcher {
        fn recorded(&self) -> Vec<LogicPkt> {
            self.pushes
                .lock()
                .unwrap_or_else(|e| e.into_inner())
                .clone()
        }
    }

    #[async_trait]
    impl Dispatcher for RecordingDispatcher {
        async fn push(
            &self,
            gateway: &str,
            channels: &[String],
            mut pkt: LogicPkt,
        ) -> Result<(), RouterError> {
            pkt.set_meta(META_DEST_SERVER, gateway);
            pkt.set_meta(META_DEST_CHANNELS, &channels.join(","));
            self.pushes
                .lock()
                .unwrap_or_else(|e| e.into_inner())
                .push(pkt);
            Ok(())
        }
    }

    fn wrapper(channel: &str) -> Session {
        Session {
            channel_id: channel.into(),
            gate_id: "wg-1".into(),
            tags: vec!["AutoGenerated".into()],
            ..Session::default()
        }
    }

    fn body_session(channel: &str) -> Session {
        Session {
            channel_id: channel.into(),
            gate_id: "wg-1".into(),
            account: "alice".into(),
            app: "kim".into(),
            ..Session::default()
        }
    }

    fn signin_pkt(channel: &str, body: &Session) -> LogicPkt {
        let mut pkt = LogicPkt::new(CMD_LOGIN_SIGN_IN, 1, Bytes::new());
        pkt.header.channel_id = channel.into();
        pkt.set_meta(META_DEST_SERVER, "wg-1");
        pkt.write_body(body);
        pkt
    }

    #[tokio::test]
    async fn second_login_dispatches_one_kickout_and_adds_body_session() {
        let cache: Arc<dyn SessionStorage> = Arc::new(MemorySessionStore::new());
        let dispatcher = Arc::new(RecordingDispatcher::default());
        let mut router = Router::new();
        router.handle(CMD_LOGIN_SIGN_IN, do_sys_login);

        router
            .serve(
                signin_pkt("wg-1_alice_1", &body_session("wg-1_alice_1")),
                dispatcher.clone(),
                cache.clone(),
                wrapper("wg-1_alice_1"),
            )
            .await
            .unwrap();
        router
            .serve(
                signin_pkt("wg-1_alice_2", &body_session("wg-1_alice_2")),
                dispatcher.clone(),
                cache.clone(),
                wrapper("wg-1_alice_2"),
            )
            .await
            .unwrap();

        let kicks: Vec<_> = dispatcher
            .recorded()
            .into_iter()
            .filter(|p| p.header.flag == Flag::Push as i32)
            .collect();
        assert_eq!(kicks.len(), 1);
        assert_eq!(kicks[0].header.command, CMD_LOGIN_SIGN_IN);
        let notify: KickoutNotify = kicks[0].read_body().unwrap();
        assert_eq!(notify.channel_id, "wg-1_alice_1");

        let stored = cache.get("wg-1_alice_2").await.unwrap();
        assert_eq!(stored.account, "alice");
        assert_eq!(stored.channel_id, "wg-1_alice_2");
        assert!(!stored.tags.iter().any(|t| t == "AutoGenerated"));
        assert_eq!(stored.app, "kim");

        let loc = cache.get_location("alice", "").await.unwrap();
        assert_eq!(loc.channel_id, "wg-1_alice_2");

        let resps: Vec<_> = dispatcher
            .recorded()
            .into_iter()
            .filter(|p| {
                p.header.flag == Flag::Response as i32 && p.header.status == Status::Success as i32
            })
            .collect();
        assert_eq!(resps.len(), 2);
    }
}
